### ISSUE TITLE
Unable to communicate to the device, authenticator error

### ISSUE THREAD

**Issue by simbalion** [Yubico/pam-u2f#100]
Thinkpad X1 Carbon, 6th Gen. Debian Stable, Yubikey Neo (just purchased). Here is the relevant log output:

[../util.c:get_devices_from_authfile(200)] Found 1 device(s) for user simba
Please touch the device.
[../util.c:do_authentication(262)] Device max index is 0
[../util.c:do_authentication(288)] Attempting authentication with device number 1
[../util.c:do_authentication(310)] Challenge: { "keyHandle": "***" }
[../util.c:do_authentication(328)] Unable to communicate to the device, authenticator error
[../pam-u2f.c:pam_sm_authenticate(256)] do_authentication returned -2
[../pam-u2f.c:pam_sm_authenticate(275)] done. [Authentication failure]
[sudo] password for simba: 

----

The same key works on a different machine, also running Debian stable

**Comment by simbalion** [comment]
should possibly merge with #99

**Comment by a-dma** [comment]
What version of pam-u2f are you running? I think Debian Stable has a fairly old version.
Is `pamu2fcfg` able to register the device? Do you have udev rules installed?

As a quick test you can try using `u2f-host` to do a [registration](https://github.com/Yubico/libu2f-host#register) and [authentication](https://github.com/Yubico/libu2f-host#authenticate)

**Comment by simbalion** [comment]
Version is 1.0.4-2. pamu2fcfg was able to register the device. I tried it with and without udev rules. It works without them on my older desktop.

**Comment by a-dma** [comment]
Have you tried using `u2f-host`? Alternatively can you try building a more recent version?

**Comment by simbalion** [comment]
Following the u2f-host testing steps here: https://developers.yubico.com/libu2f-host/ I was met with full success, so it would seem the problem is specific to pam-u2f.so. Is there a way to get more verbose debug information?

**Comment by a-dma** [comment]
What is in your service configuration file? Can you try re-registering the device?

Newer versions of `pam_u2f` also set `libu2f-host` in debug mode and produce more output.

**Comment by simbalion** [comment]
> What is in your service configuration file?

Please specify what file you're asking about

> Can you try re-registering the device?

I will try that, I was worried about the possible consequences.

**Comment by simbalion** [comment]
Re-registering fixed the issue

**Comment by a-dma** [comment]
Glad to hear that.

Sure, feel free to attach the non-working file. I'll have a look.
