### ISSUE TITLE
problem with Building from Git instructions on Ubuntu 18.04

### ISSUE THREAD

**Issue by metebalci** [Yubico/pam-u2f#101]
If the Building from Git instructions is followed (for pam_u2f-1.0.7), at the `./configure` (in Building section) following error is observed: 
```
./configure: line 12696: syntax error near unexpected token `LIBU2FHOST,'
./configure: line 12696: `PKG_CHECK_MODULES(LIBU2FHOST, u2f-host, , )'
```
Running `autoreconf --reinstall` again after installing the libu2f-host and -server packages resolves the problem. I am not sure if this is obvious for many but it can be good to clarify this in the instructions.

**Comment by a-dma** [comment]
The link to "build as usual" was supposed to remind you to add those dependencies as well. I guess things have changed over time and became a bit confused. I've added the two missing dependencies to that line. Thanks for reporting this.
