### ISSUE TITLE
nouserok behavior when no authentication file exists

### ISSUE THREAD

**Issue by ghuysmans** [Yubico/pam-u2f#103]
Hi,

The `nouserok` flag doesn't prevent authentication from failing with `PAM_AUTHINFO_UNAVAIL` when no authfile exists.

On my system, I'd like to allow users to configure U2F by simply creating _their own_ `u2f_keys` file, without forcing everyone to have it. Would it make sense to update the existing flag's behavior, or is a new flag (e.g. `noauthok`) a better idea?

**Comment by stovocor** [comment]
Is it possible that your issue is fixed by now? The current documentation states

> Set to enable authentication attempts to succeed even if the user trying to authenticate is not found inside authfile or if authfile is missing/malformed.

When I remove `~/.config/Yubico`, authentication does not fail.

**Comment by ghuysmans** [comment]
Great, then! Thanks for telling me :)
