### ISSUE TITLE
pam_u2f unable to discover device even though pamu2fcfg and u2f-host can

### ISSUE THREAD

**Issue by mr-infty** [Yubico/pam-u2f#104]
I can successfully register my Feitian U2F USB key with

    pamu2fcfg > ~/.config/Yubico/u2f_keys

but when I enable pam_u2f.so for sudo by putting the line

     auth       sufficient     /opt/local/lib/pam/pam_u2f.so debug

into `/etc/pam.d/sudo`, I get the following debug output:

    debug(pam_u2f): util.c:191 (get_devices_from_authfile): Found 1 device(s) for user nico
    debug(pam_u2f): pam-u2f.c:317 (pam_sm_authenticate): Using file '/var/run/user/0/pam-u2f-authpending' for emitting touch request notifications
    debug(pam_u2f): util.c:266 (do_authentication): Unable to discover device(s), cannot find U2F device
    debug(pam_u2f): pam-u2f.c:347 (pam_sm_authenticate): do_authentication returned -2
    debug(pam_u2f): pam-u2f.c:386 (pam_sm_authenticate): done. [authentication error]

**Comment by a-dma** [comment]
Do you get a different result if you disable `authpending_file`?
Does a manual authentication done using `u2f-server` and `u2f-host` work?

**Comment by mr-infty** [comment]
Sorry, for the late response:

1. Disabling `authpending_file` by supplying the option `authpending_file=` doesn't give a different result (except a message saying that `authpending_file` has been disabled).
2. Trying manual verification by supplying the option `manual` fails with the error message

        debug(pam_u2f): pam-u2f.c:347 (pam_sm_authenticate): do_authentication returned -1
        debug(pam_u2f): pam-u2f.c:386 (pam_sm_authenticate): done. [authentication error]
     even though the key starts flashing and gives a response when I supply the challenge to it using `u2f-host -aauthenticate`.
3. Trying manual verification using `u2f-server` gives a different, and weird error: If I run

        u2f-server -k <key-handle> -i pam://myappid -o pam://myappid
     it gives the error

        open: No such file or directory.

**Comment by a-dma** [comment]
It's hard to tell whether it's the device that isn't working or the tools without more debug output.

Also, you're missing the `-a authenticate` flag on `u2f-server`.
Try following this manual example https://github.com/Yubico/libu2f-server#usage

**Comment by mr-infty** [comment]
The key works perfectly fine if I use it to authenticate against websites, so I doubt that it's a problem with the hardware.

I tried following the example given on the website that you linked, more specifically, I tried performing a **REGISTRATION** operation, but I got stuck at the last step: when I paste in the response generated by the key back into the `u2f-server` application, nothing happens. To be more precise, I get the "terminal beep" sound, and after that the window refuses to accept any input.

**Comment by a-dma** [comment]
What OS are you using for this?
Is it a regular terminal emulator?
Are you sending in and EOF character (Ctrl-D) after pasting the data?

The fact that the terminal window doesn't accept any input afterward is very weird.

**Comment by mr-infty** [comment]
I'm on macOS High Sierra, using the standard `Terminal.app`. I do send an EOF character after I input the challenge into the `u2f-host` window, but I *don't* after I input the response into the `u2f-server` windows because I can't: the terminal becomes unresponsive after pasting in the response.

**Comment by a-dma** [comment]
So, apparently macOS has a problem with reading more than 1024 bytes from stdin. If you run `wc` on the amount of text that gets pasted in you should see that it's 1024 characters.

People suggest to use `pbaste` but that's a bit awkward to use in this scenario. If you split the response in chunks that are smaller than 1024 by adding carriage returns in the middle of it you can get away with it. I know it sounds horrible but it seems to be a known issue with macOS.

**Comment by a-dma** [comment]
Ok, small amount of progress there.

Do you see the message `Now, please enter the response(s) below, one per line.`? It might be that the line buffering issue above is preventing the whole response from getting to the module.

**Comment by mr-infty** [comment]
Yes, I do see that line. Moreover, after I paste the response and hit enter, only *part* of that response is echoed back to the console. More precisely, only the first 256 characters get echoed back. Thus, the text in my console looks like this

    Now, please enter the response(s) below, one per line.
    [0]: <the response>
    <the first 256 characters of the response>
    debug(pam_u2f): pam-u2f.c:347 (pam_sm_authenticate): do_authentication returned -1
    debug(pam_u2f): pam-u2f.c:386 (pam_sm_authenticate): done. [authentication error]

**Comment by a-dma** [comment]
I suspect that it is something related to that. Only part of the response seems to make its way to the module.
Are you able to modify and build the source code? If so you could add a debug print at https://github.com/Yubico/pam-u2f/blob/master/util.c#L481 with the content of `response`.

**Comment by mr-infty** [comment]
Ok, I finally got around to compile this thing. As it turns out, the string `response` is only 255 chars long, which is shorter than the actual response that I post in.

**Comment by a-dma** [comment]
That is a suspicious number, but I'm not sure how else I can help you with this.
It sounds like your terminal is playing some tricks on you? Maybe you can try the same setup in a Linux VM?

**Comment by raku-cat** [comment]
I'm getting a similar problem to this on arch Linux. Using pamu2fcfg or trying to login only works once, the device has to be reseated from that point forward to work again, else there's the same "unable to discover devices" error, the key meanwhile does still work otherwise, but pam_u2f will not detect it again until the device is unplugged and plugged back in.

**Comment by a-dma** [comment]
1.1.0 was published today with quite a few changes. I'll close this for now. Please reopen if the issue still applies.
