### ISSUE TITLE
u2f support for openssh?

### ISSUE THREAD

**Issue by sknewcomb** [Yubico/pam-u2f#109]
Looking to get either my yubico or google titan key working with pam-u2f but it seems open ssh doesn't support it. The most recent thing I can find is from https://github.com/Yubico/pam-u2f/issues/12. 

Is there any kind of recent update that isn't well known for support of u2f in openssh?

End Goal: Be able to setup u2f authentication for remote ssh servers for better security.

**Comment by a-dma** [comment]
Not that I know of, this would require modifications to SSH. I'll close this and redirect further discussion towards #12.

**Comment by nivoc** [comment]
Soon possible: https://marc.info/?l=openssh-unix-dev&m=157259802529972&w=2

**Comment by Merith-TK** [comment]
u2f is supported as of openssh 8.2
