### ISSUE TITLE
Unable to use Yubikey U2F for Linux login

### ISSUE THREAD

**Issue by Ralphie089** [Yubico/pam-u2f#110]
Hi, I recently installed Linux Mint 19.1 (I'm pretty new to Linux) and tried to add my Yubikey as a 2FA for login (using U2F), following the instructions on the Yubico website: [https://support.yubico.com/support/solutions/articles/15000011356-ubuntu-linux-login-guide-u2f](url)

I managed to add my Yubikey (as well as backup Yubikey) and successfully tested them with sudo (section 4.1 in link above). However, after configuring the system to require the Yubikey for login (`sudo nano /etc/pam.d/lightdm`; see section 4.2) and subsequently rebooting the system, I was unable to login. Entering the password doesn't trigger the Yubikey for input (no light on Yubikey), so I locked myself out. I managed to remove the `auth       required   pam_u2f.so` line via root shell prompt after booting into recovery mode to be able to login to Linux again using only the password (isn't this a risk in terms of security btw?).

Enabling debug mode resulted in the following:

debug(pam_u2f): ../pam-u2f.c:94 (parse_cfg): called.
debug(pam_u2f): ../pam-u2f.c:95 (parse_cfg): flags 0 argc 2
debug(pam_u2f): ../pam-u2f.c:97 (parse_cfg): argv[0]=debug
debug(pam_u2f): ../pam-u2f.c:97 (parse_cfg): argv[1]=debug_file=/var/log/pam_u2f.log
debug(pam_u2f): ../pam-u2f.c:99 (parse_cfg): max_devices=0
debug(pam_u2f): ../pam-u2f.c:100 (parse_cfg): debug=1
debug(pam_u2f): ../pam-u2f.c:101 (parse_cfg): interactive=0
debug(pam_u2f): ../pam-u2f.c:102 (parse_cfg): cue=0
debug(pam_u2f): ../pam-u2f.c:103 (parse_cfg): nodetect=0
debug(pam_u2f): ../pam-u2f.c:104 (parse_cfg): manual=0
debug(pam_u2f): ../pam-u2f.c:105 (parse_cfg): nouserok=0
debug(pam_u2f): ../pam-u2f.c:106 (parse_cfg): openasuser=0
debug(pam_u2f): ../pam-u2f.c:107 (parse_cfg): alwaysok=0
debug(pam_u2f): ../pam-u2f.c:108 (parse_cfg): authfile=(null)
debug(pam_u2f): ../pam-u2f.c:109 (parse_cfg): authpending_file=(null)
debug(pam_u2f): ../pam-u2f.c:110 (parse_cfg): origin=(null)
debug(pam_u2f): ../pam-u2f.c:111 (parse_cfg): appid=(null)
debug(pam_u2f): ../pam-u2f.c:112 (parse_cfg): prompt=(null)
debug(pam_u2f): ../pam-u2f.c:157 (pam_sm_authenticate): Origin not specified, using "pam://ralf-N551JB"
debug(pam_u2f): ../pam-u2f.c:169 (pam_sm_authenticate): Appid not specified, using the same value of origin (pam://ralf-N551JB)
debug(pam_u2f): ../pam-u2f.c:180 (pam_sm_authenticate): Maximum devices number not set. Using default (24)
debug(pam_u2f): ../pam-u2f.c:198 (pam_sm_authenticate): Requesting authentication for user ralf
debug(pam_u2f): ../pam-u2f.c:209 (pam_sm_authenticate): Found user ralf
debug(pam_u2f): ../pam-u2f.c:210 (pam_sm_authenticate): Home directory for ralf is /home/ralf
debug(pam_u2f): ../pam-u2f.c:217 (pam_sm_authenticate): Variable XDG_CONFIG_HOME is not set. Using default value ($HOME/.config/)
debug(pam_u2f): ../pam-u2f.c:245 (pam_sm_authenticate): Using default authentication file /home/ralf/.config/Yubico/u2f_keys
debug(pam_u2f): ../util.c:42 (get_devices_from_authfile): Cannot open file: /home/ralf/.config/Yubico/u2f_keys (No such file or directory)
debug(pam_u2f): ../pam-u2f.c:287 (pam_sm_authenticate): Unable to get devices from file /home/ralf/.config/Yubico/u2f_keys
debug(pam_u2f): ../pam-u2f.c:386 (pam_sm_authenticate): done. [Authentication service cannot retrieve authentication info]

Any ideas how to resolve this issue?

**Comment by a-dma** [comment]
It looks like the file where you stored the credentials can't be found or has the wrong permissions.

Make sure that `/home/ralf/.config/Yubico/u2f_keys` exists and is readable.

I recommend setting this up either in VM or as a separate service and using `pamtester` first as having to manually mount the hard drive is annoying to say the least.

**Comment by apezuela** [comment]
I have the same issue. I tried with chmod +777 in the file, and nothing. I'm using ubuntu.

**Comment by corbolais** [comment]
@apezuela Yes, using "$HOME" or even "~" with pam-u2f authfile will not work as path member. 

Using an absolute path for your user will work for one single user. However, it will fail if there will ever be another user trying to use pam-u2f. 

Use my PR #125 to get the 'relative path for per user key files' feature, if you want.
