### ISSUE TITLE
PAM authentication times out

### ISSUE THREAD

**Issue by redradrat** [Yubico/pam-u2f#114]
USB-A dongle-type U2F devices (HyperFIDO Titanium, Feitian U2F NFC Key) authentication times out and fails after upgrade to Linux 5.0.0 (could be different component too, did a batch upgrade :woman_facepalming: )

pamu2fcfg output:
```
╭─[XXXXXXXX@XXXXXXXXXX] ~ 
╰─➤ :( [ pamu2fcfg                                                               ] 00:21 
No U2F device available, please insert one now, you have 10 seconds
Device found!
Unable to generate registration challenge, error in transport layer (-2)
```

Appears to detect the device properly and then fails to communicate.

Cord-connected device Feitian U2F Multi-Inteface works.

```
╭─[XXXXXXXX@XXXXXXXXXX] ~ 
╰─➤ :( [ pamu2fcfg                                                               ] 00:22
No U2F device available, please insert one now, you have 12 seconds
Device found!
XXXXXXXX:abcde...
```

**Comment by a-dma** [comment]
Can you provide debug output by calling `pamu2fcfg -d`?

There have been a couple of releases of libu2f-host recently. Make sure you have the latest one (1.1.9) since the previous one broke compatibility with a few devices.

**Comment by redradrat** [comment]
@a-dma Thanks for the pointer! Didn't realize... probably was the libu2f-host... Flagged the arch package out of date... let's see :) Will give feedback when package is updated to 1.1.8

**Comment by a-dma** [comment]
No worries, but make sure it's `1.1.9`!

**Comment by redradrat** [comment]
@a-dma yup... typo ;) ty

**Comment by redradrat** [comment]
Working again with 1.1.9. Thanks!
