### ISSUE TITLE
Aggregate multiple entries for the same user in the mapping file

### ISSUE THREAD

**Issue by gktrk** [Yubico/pam-u2f#117]
If a user enters two entries in the mapping file in the following fashion:

```
<username1>:<KeyHandle1>,<UserKey1>
<username1>:<KeyHandle2>,<UserKey2>
```

only the last entry works as per https://github.com/Yubico/pam-u2f/blob/f8756e72299205fbc23a483c940dc1ad44e125b2/util.c#L114. Is there any reason beyond the expected code complexity as to why it works this way? I'd be interested in submitting a patch to aggregate multiple entries for one particular user across multiple lines but I wanted to check with the upstream first.

**Comment by a-dma** [comment]
That is because the idea is to only have one line per user. If you want to register multiple devices you should append the information to the same line separated by a `:`. The format is described in the `README` file.

**Comment by gktrk** [comment]
I was wondering if you are open to the idea of aggregating multiple lines that belong to the same user. I understand that it's ultimately an upstream decision.

**Comment by a-dma** [comment]
What kind of problem would that solve is it just usability? Given that the functionality already exists I think there should be a fairly compelling reason to "duplicate" it.

**Comment by gktrk** [comment]
I have to yield to the fact that it would break backward compatibility (i.e. users appending new entries with the assumption that it will **override** the previous entries, not **aggregate**). Thanks for your consideration.
