### ISSUE TITLE
Cue Promt not showing correctly

### ISSUE THREAD

**Issue by maxbax0808** [Yubico/pam-u2f#122]
My config is as follows:
auth required pam_u2f.so nouserok nodetect cue [cue_promt=hey idiot]

I have tried it with many other variations, having the cue behind the cue_promt, having " or ' around the text, etc.
No matter what I do, there will always be the Message "Please touch the device."

Any Ideas?

**Comment by a-dma** [comment]
if that's literally your config then you're misspelling "prompt"

**Comment by maxbax0808** [comment]
With that you are correct, but even if I copy paste it from the readme.adoc the wrong message appears...
Would the output of the Debug be of any help?

**Comment by a-dma** [comment]
This configuration works for me:
`auth sufficient pam_u2f.so authfile=/path/to/authfile cue [cue_prompt=hello world]`.

Are you building this yourself? The `cue_prompt` option is currently unreleased.

**Comment by maxbax0808** [comment]
I am using Version 1.0.8-2 from the official Arch Community Repo...
So you are saying the cue_prompt is comming in a future Version?
I only saw it here on and thought it would be in the currently released Version...

**Comment by a-dma** [comment]
Correct, currently the latest release is from 2019-06-04 and the cue_prompt code was merged on 2019-07-05.

**Comment by corbolais** [comment]
For me

    auth sufficient pam_u2f.so authfile=/path/to/authfile cue [cue_prompt=hello world]

isn't working. But

    auth sufficient pam_u2f.so authfile=/path/to/authfile [prompt=hello world]

is.

**Comment by a-dma** [comment]
Those are two different parameters.

**Comment by corbolais** [comment]
> Those are two different parameters.

Sure. It is the only configuration resulting in the intented behaviour, however.

**Comment by a-dma** [comment]
I see, but that is the expected behavior for 1.0.8, no? As I mentioned a few messages above the `cue_prompt` option is not in that version.
