### ISSUE TITLE
Works very inconsistently and only ever with debug

### ISSUE THREAD

**Issue by raku-cat** [Yubico/pam-u2f#128]
I have this set up in such a way that I can use my yubikey or my password to authenticate. This is the line in `/etc/pam.d/system-auth`
```
auth      sufficient  pam_u2f.so    interactive cue
```
When I try a test command (`sudo echo`), the prompt comes up `Insert your U2F device, then press ENTER.`, and after I press enter it hangs until the timeout finishes.
<details>
<summary>Log</summary>

```Insert your U2F device, then press ENTER.
USB send: 00ffffffffffffffffffffff000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
USB write returned 65
now trying with timeout 2
now trying with timeout 4
now trying with timeout 8
now trying with timeout 16
now trying with timeout 32
now trying with timeout 64
now trying with timeout 128
now trying with timeout 256
now trying with timeout 512
now trying with timeout 1024
now trying with timeout 2048
now trying with timeout 4096
USB read rc read 64
debug(pam_u2f): util.c:271 (do_authentication): Unable to discover device(s), cannot find U2F device
debug(pam_u2f): pam-u2f.c:371 (pam_sm_authenticate): do_authentication returned -2
debug(pam_u2f): pam-u2f.c:410 (pam_sm_authenticate): done. [Authentication failure]
```
</details>
If I add debug to the arguments, I can typically get it to work 3 or 4 times without having to replug the key, after which it will arbitrarily decide to stop working and timeout.
In no case does it work at all without debug enabled at the moment, though I do recall playing with this a few months ago and actually having it work without debug being enable, but would time out after working once and require a replug for every auth prompt. 

I'm running Arch linux with pam-u2f version 1.0.8.

Edit: Basically having the exact same issue as #102 .  
In my case I did have to do some finagling with my mobo settings to get the front usb (they're 3.0) ports working, however everything on them works fine now, this is the only device that has issues. 
The yubikey works fine in every other aspect as with the previous issue, though when authenticating with it in browsers I do sometimes encounter the problem of it only working once or twice and then needing to be replugged.
Trying the command
 `echo -n '{"challenge": "rBSYJTllTZheodo2ch2Gi59QKvCMKePhqD_fia_MwNo", "version": "U2F_V2", "appId": "https://demo.yubico.com"}' | u2f-host -d -a register -o https://demo.yubico.com` 
results in a timeout every single time I try it, sometimes the light on the key will flash as it does when it's recognized and I'm cued to touch it, but touching it does nothing, the light turns solid and stays on for a few seconds as the command times out.

**Comment by a-dma** [comment]
Issues like this are a bit hard to debug since it's difficult to know what the kernel is doing. Any chance you can try to reproduce this using some other USB port?

Alternatively, if you're willing to build `HEAD` on `master`, that re-implements some of that logic (it uses `libfido2`). That could help us understand whether it is a purely hardware problem, a software one, or a mix of both.

**Comment by raku-cat** [comment]
Sorry that I opened this and then proceeded to vanish, I'm pretty sure this was down to a hardware bug.  The mobo I was using at the time of this bug report I had ALWAYS had issues with the USB3 ports on, very largely on the front ones but occasionally on the back ports as well, with some mobo tweaking I could kind of get flashdrives working consistently on the front, but ultimately I ended up upgrading most of my computer and the issue is gone. Sorry if anyone was lurking this issue and was hoping for a better resolution :(

**Comment by a-dma** [comment]
No worries. Thanks for reporting back and glad to hear that, even though it required some drastic measures, the issue is now resolved.

**Comment by lseifert** [comment]
I had similar problems to the ones noted above, on switching from USB 3 to USB 2 ports it appears to work perfectly consistently.
