### ISSUE TITLE
Ubuntu Linux Login Guide - U2F edit

### ISSUE THREAD

**Issue by 4x0v7** [Yubico/pam-u2f#129]
I have followed the guide available [here](https://support.yubico.com/support/solutions/articles/15000011356-ubuntu-linux-login-guide-u2f) and successfully setup U2F.

While I was following through the instructions, I noticed a small typo:

> You will need to append the PAM file's configuration to have " authfile=/etc/Yubico/u2f_ " added to the end.

I believe this should read:
> You will need to append the PAM file's configuration to have "authfile=/etc/Yubico/u2f_keys" added to the end.

It was also not clear to me from the article where the `authfile=` string was meant to go.

After looking at the examples on <https://developers.yubico.com/pam-u2f/> I found this configuration goes at the end of `auth       required   pam_u2f.so`

The guide could be updated with something like:
```
1. Open Terminal.
2. Run: sudo nano /etc/pam.d/sudo
3. Add the line below after the “@include common-auth” line.

auth       required   pam_u2f.so

Note: If you have moved the u2f_keys file to /etc/Yubico/u2f_keys as suggested, you will need to append "authfile" to the PAM configuration:

auth       required   pam_u2f.so   authfile=/etc/Yubico/u2f_keys
```

**Comment by nevun** [comment]
Thank you! Issues and/or improvements to that guide should be submitted as feedback on the page (see the link at the bottom of the guide). I have done that for you this time though so you do not have to ;) 
Submitting things there creates a support ticket for tracking so I will close this one. Thanks again!

**Comment by 4x0v7** [comment]
Ah I see I should have said No to "Did you find this article useful?" and submitted feedback.
I did find the article useful, hence I didn't think to click No. Thank you!
