### ISSUE TITLE
pam-u2f make failure after update on November 9

### ISSUE THREAD

**Issue by iamyanyyy** [Yubico/pam-u2f#134]
Making all in .
make[1]: Entering directory '/home/thtfit/pam-u2f'
/bin/bash /home/thtfit/pam-u2f/build-aux/missing a2x --format=manpage -L -a revdate="Version 1.0.9" man/pam_u2f.8.txt
a2x: ERROR: "xsltproc"  --stringparam callout.graphics 0 --stringparam navig.graphics 0 --stringparam admon.textlabel 1 --stringparam admon.graphics 0  "/etc/asciidoc/docbook-xsl/manpage.xsl" "/home/thtfit/pam-u2f/man/pam_u2f.8.xml" returned non-zero exit status 5
Makefile:1025: recipe for target 'man/pam_u2f.8' failed
make[1]: *** [man/pam_u2f.8] Error 1
make[1]: Leaving directory '/home/thtfit/pam-u2f'
Makefile:596: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

**Comment by a-dma** [comment]
It appears to work for me (albeit xsltproc is now quite slow).

According to the man page, exit status `5` means problems with the stylesheet. What is the content of `/etc/asciidoc/docbook-xsl/manpage.xsl`?

For reference this is what I am running
```bash
$  a2x --version
a2x 8.6.10
$  xsltproc --version
Using libxml 20904, libxslt 10133 and libexslt 820
xsltproc was compiled against libxml 20904, libxslt 10133 and libexslt 820
libxslt 10133 was compiled against libxml 20904
libexslt 820 was compiled against libxml 20904```

Also you can disable manpage generation `./configure --disable-man` but it would be nice to know if something broke.
