### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by Keruspe** [Yubico/pam-u2f#140]
Hi,

Would it be possible to get a new released based on libfido2?

**Comment by a-dma** [comment]
Yes, I have a new release planned "soon". I'd like to merge the SSH key support now that OpenSSH has been released and make sure that everything is still sane first.

Unfortunately I don't have an actual date yet.

**Comment by maximbaz** [comment]
Hi @a-dma, a friendly ping to ask if a new release is still in the plans? 🙂 
Do you need some help with testing ssh branch perhaps? If so I would be happy to use it for some days and report if I spot anything.

**Comment by a-dma** [comment]
Hi, yes it is indeed still planned, just lots of other things happening and I haven't managed to give this the amount of testing that I'd like. Sorry for the delay.

I have just now merged the `ssh_format` branch to master. Any help in testing that is more than welcome.
I'll be updating the README file and the man pages next, so beware of some currently incorrect information there.

For anybody interested in helping with some testing, things to look for are:
- backwards compatibility, making sure that moving to libfido2 doesn't break current setups (keeping in mind that the released version still uses `libu2f-{server,host}`)
- testing the SSH support, do the options make sense and does it do what you expect
- general stability

I'll get there but I have limited time to spend on this project. All help is welcome :)

Thanks

**Comment by maximbaz** [comment]
Just wanted to let you know that I switched to a build from `master` branch after your comment, my existing setup didn't break and I haven't noticed any single issue. If I spot something I will of course let you know, but so far everything looks really good 👍 

I didn't test SSH support, can try once the documentation becomes available 🙂

**Comment by a-dma** [comment]
Good to hear, thanks a lot. Appreciate the help.
I've added in a bunch of tests a couple of days ago and those should help building more confidence that old configurations will keep working. I'll get on the README as soon as I have a spare minute. I'll try to remember mentioning this issue so that notifications are generated.

**Comment by a-dma** [comment]
I've updated the documentation so that it reflects the current status of things.
Unless somebody has encountered issues I'll try to schedule a release soon.

**Comment by a-dma** [comment]
It took a bit longer than anticipated, apologies for that.

However, 1.1.0 is out. Closing this.
