### ISSUE TITLE
`authpending` is no longer needed

### ISSUE THREAD

**Issue by maximbaz** [Yubico/pam-u2f#145]
Hey @a-dma, we implemented `authpending` marker for me to use in [yubikey-touch-detector](https://github.com/maximbaz/yubikey-touch-detector) and it worked quite well, but today I managed to find another way of detecting that YubiKey is waiting for a touch because of U2F operation without using this marker: I noticed that if I monitor file access on `/dev/hidraw*` devices that are labeled with "YubiKey", then one of them gets OPEN event when YubiKey starts waiting for a touch and CLOSE event when it stops waiting for a touch.

This approach seems to work quite reliably to me personally, and is able to detect even more events ( for example browsers requesting touch on https://webauthn.io ), so I've pushed an update and will see if users report any issues.

If everything goes well, I think we could remove the `authpending` before releasing the next version of `pam-u2f`, unless of course you prefer to keep it for other reasons.

I thank you again for our collaboration on introducing `authpending` functionality, it worked really well for many people for years!

**Comment by a-dma** [comment]
Ah good to know, thanks for reporting this. Glad that it has served its purpose.

As always with features like this it's hard to know if somebody's workflow is relying on it and it's never easy to drop support. I'll keep it around for now, maybe soft deprecate it over time.
