### ISSUE TITLE
Login does not work with eWBM Goldengate G310

### ISSUE THREAD

**Issue by chrisrot69** [Yubico/pam-u2f#147]
Hi,

I try to get my new G310 to work with pam_u2f, but without success.
Creating a key with pamu2fcfg works, however.

When I try to sudo -i, the key does not flash orange and I get the following debug info
`USB send: 00ffffffff8600083276b09f17946ddb000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
USB write returned 65
now trying with timeout 2
now trying with timeout 4
now trying with timeout 8
USB read rc read 64
USB recv: ffffffff8600113276b09f17946ddb0007000a0202086b0d00000000000000000000000000000000000000000000000000000000000000000000000000000000
device /dev/hidraw0 discovered as 'eWBM Security Key(Goldengate G310)'
  version (Interface, Major, Minor, Build): 2, 2, 8, 107  capFlags: 13
JSON: { "keyHandle": "4MlEW9Hunkonw1YMDAo0lZ3rkQiPdmOvCAxeWAMNWJAHVRLoGE9EhwrEUJx20sjwgyeAV7RksreGrh35IhLUKJVk497g-srcC-q_6F2uNkIh7k4UP9DBUv719yhtZLA6VUFIZ_PMV6oIwmSchkc2_r6y6Aakqv4SPliDvShh0tkhnhLMqweBOyz1c9XM0nB8lK8ExsQh43tAm_tfL-IV2ZnQLz0kR5jDNsP3p3WChyS3TNnt6vg-4AAuyyWhvkDX", "version": "U2F_V2", "challenge": "I21RA2_R4vyuxoMNk6t_bTBzrBw-TBS3hNBehGbwzNI", "appId": "pam:\/\/heartofgold" }
JSON challenge URL-B64: I21RA2_R4vyuxoMNk6t_bTBzrBw-TBS3hNBehGbwzNI
client data: { "challenge": "I21RA2_R4vyuxoMNk6t_bTBzrBw-TBS3hNBehGbwzNI", "origin": "pam:\/\/heartofgold", "typ": "navigator.id.getAssertion" }
JSON: { "keyHandle": "4MlEW9Hunkonw1YMDAo0lZ3rkQiPdmOvCAxeWAMNWJAHVRLoGE9EhwrEUJx20sjwgyeAV7RksreGrh35IhLUKJVk497g-srcC-q_6F2uNkIh7k4UP9DBUv719yhtZLA6VUFIZ_PMV6oIwmSchkc2_r6y6Aakqv4SPliDvShh0tkhnhLMqweBOyz1c9XM0nB8lK8ExsQh43tAm_tfL-IV2ZnQLz0kR5jDNsP3p3WChyS3TNnt6vg-4AAuyyWhvkDX", "version": "U2F_V2", "challenge": "I21RA2_R4vyuxoMNk6t_bTBzrBw-TBS3hNBehGbwzNI", "appId": "pam:\/\/heartofgold" }
JSON app_id pam://heartofgold
JSON: { "keyHandle": "4MlEW9Hunkonw1YMDAo0lZ3rkQiPdmOvCAxeWAMNWJAHVRLoGE9EhwrEUJx20sjwgyeAV7RksreGrh35IhLUKJVk497g-srcC-q_6F2uNkIh7k4UP9DBUv719yhtZLA6VUFIZ_PMV6oIwmSchkc2_r6y6Aakqv4SPliDvShh0tkhnhLMqweBOyz1c9XM0nB8lK8ExsQh43tAm_tfL-IV2ZnQLz0kR5jDNsP3p3WChyS3TNnt6vg-4AAuyyWhvkDX", "version": "U2F_V2", "challenge": "I21RA2_R4vyuxoMNk6t_bTBzrBw-TBS3hNBehGbwzNI", "appId": "pam:\/\/heartofgold" }
JSON keyHandle URL-B64: 4MlEW9Hunkonw1YMDAo0lZ3rkQiPdmOvCAxeWAMNWJAHVRLoGE9EhwrEUJx20sjwgyeAV7RksreGrh35IhLUKJVk497g-srcC-q_6F2uNkIh7k4UP9DBUv719yhtZLA6VUFIZ_PMV6oIwmSchkc2_r6y6Aakqv4SPliDvShh0tkhnhLMqweBOyz1c9XM0nB8lK8ExsQh43tAm_tfL-IV2ZnQLz0kR5jDNsP3p3WChyS3TNnt6vg-4AAuyyWhvkDX
USB send: 000007000a8100010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
USB write returned 65
now trying with timeout 2
now trying with timeout 4
now trying with timeout 8
USB read rc read 64
USB recv: 0007000a810001000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
Sorry, try again.
`

My /etc/pam.d/sudo-i file is
`# File autogenerated by pamd_mimic in pam eclass

auth    require         pam_u2f.so debug 
#auth   include         system-auth
account include         system-auth
session include         system-auth
`
I tried several options like pinverification, userverification, etc.

When I do a u2f-host test with 
`echo -n '{"challenge": "rBSYJTllTZheodo2ch2Gi59QKvCMKePhqD_fia_MwNo", "version": "U2F_V2", "appId": "pam://heartofgold"}' | u2f-host -d -a register -o pam://heartofgold`
the key flashes orange until it registers my finger print.
The debug info is
`USB send: 00ffffffff860008a0fa5f443be98382000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
USB write returned 65
now trying with timeout 2
now trying with timeout 4
now trying with timeout 8
USB read rc read 64
USB recv: ffffffff860011a0fa5f443be98382000700090202086b0d00000000000000000000000000000000000000000000000000000000000000000000000000000000
device /dev/hidraw0 discovered as 'eWBM Security Key(Goldengate G310)'
  version (Interface, Major, Minor, Build): 2, 2, 8, 107  capFlags: 13
JSON: { "challenge": "rBSYJTllTZheodo2ch2Gi59QKvCMKePhqD_fia_MwNo", "version": "U2F_V2", "appId": "pam:\/\/heartofgold" }
JSON challenge URL-B64: rBSYJTllTZheodo2ch2Gi59QKvCMKePhqD_fia_MwNo
client data: { "challenge": "rBSYJTllTZheodo2ch2Gi59QKvCMKePhqD_fia_MwNo", "origin": "pam:\/\/heartofgold", "typ": "navigator.id.finishEnrollment" }
JSON: { "challenge": "rBSYJTllTZheodo2ch2Gi59QKvCMKePhqD_fia_MwNo", "version": "U2F_V2", "appId": "pam:\/\/heartofgold" }
JSON app_id pam://heartofgold
USB send: 00000700098300490001030000004006b893d62b5c17d678e800777675b106e4f8c76a1fc0f98861d4cb0ec53e9cbd378663bad2ddab7b085bb90a5179cade51
USB write returned 65
USB send: 000007000900596d46a14fdae6a5dd77e20ecac20000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
USB write returned 65
now trying with timeout 2
now trying with timeout 4
now trying with timeout 8
now trying with timeout 16
now trying with timeout 32
now trying with timeout 64
now trying with timeout 128
now trying with timeout 256
now trying with timeout 512
now trying with timeout 1024
USB read rc read 64
USB recv: 000700098303ab05040362e82ec73608a3e999113bc5f91d55898ea3672f0690a197c90e9a203c4c5d54ccb641394266cbfa8218b1a2b09212e53abd12c955f0
now trying with timeout 2
now trying with timeout 4
USB read rc read 64
USB recv: 00070009007daa318be6daff48e8c028863509071d8f98785ba4bd544b5348ee49a8a6eaaa6cf65f17a35d3eb7922d9a468aec05918bccca65c092113a9465e3
now trying with timeout 2
now trying with timeout 4
USB read rc read 64
USB recv: 000700090174c456b16ef93859bc62719483e64a2a5d62a517e8fdf5d7dc8e0a1e1d81dd59023c293d76bdedca8811b830e59d5e1dbb4c9b0e13c78ff672a725
now trying with timeout 2
now trying with timeout 4
USB read rc read 64
USB recv: 000700090229455852539c5a9df6e25ebcd1ba911bbeba477553feb15aeb9394882ede5e5b156fefc0bc3893da3bc195a0a8ab6c93dfb77a6b1577fb533c19dc
now trying with timeout 2
now trying with timeout 4
USB read rc read 64
USB recv: 000700090346182a710435063b40a310918665a1d2ce4e9a85f2f0c95b833082025b30820201a003020102020900a09b1d5d2223b639300a06082a8648ce3d04
now trying with timeout 2
now trying with timeout 4
USB read rc read 64
USB recv: 000700090403023081af310b3009060355040613024b523111300f06035504080c0853656f756c2d53693113301106035504070c0a47616e676e616d2d477531
now trying with timeout 2
now trying with timeout 4
USB read rc read 64
USB recv: 0007000905173015060355040a0c0e6557424d20436f2e2c204c74642e31223020060355040b0c1941757468656e74696361746f72204174746573746174696f
now trying with timeout 2
now trying with timeout 4
USB read rc read 64
USB recv: 00070009066e311c301a06035504030c136557424d204341204365727469666963617465311d301b06092a864886f70d010901160e696e666f40652d77626d2e
now trying with timeout 2
now trying with timeout 4
USB read rc read 64
USB recv: 0007000907636f6d301e170d3138303732333032303533385a170d3233303732313032303533385a3081b5310b3009060355040613024b523111300f06035504
now trying with timeout 2
now trying with timeout 4
USB read rc read 64
USB recv: 0007000908080c0853656f756c2d53693113301106035504070c0a47616e676e616d2d477531173015060355040a0c0e6557424d20436f2e2c204c74642e3122
now trying with timeout 2
now trying with timeout 4
USB read rc read 64
USB recv: 00070009093020060355040b0c1941757468656e74696361746f72204174746573746174696f6e3122302006035504030c196557424d204649444f2055324620
now trying with timeout 2
now trying with timeout 4
USB read rc read 64
USB recv: 000700090a4365727469666963617465311d301b06092a864886f70d010901160e696e666f40652d77626d2e636f6d3059301306072a8648ce3d020106082a86
now trying with timeout 2
now trying with timeout 4
USB read rc read 64
USB recv: 000700090b48ce3d0301070342000463b6636e960b27170aa169c1e8e313a7d03562aab90f1bd7787bb625b14df03a7bdd8674ebd73837fa9f00691fbd42476b
now trying with timeout 2
now trying with timeout 4
USB read rc read 64
USB recv: 000700090c43b33efdbd945c8372cfa42ef44df8300a06082a8648ce3d0403020348003045022100bfd882289b3f12108849b8fccfa2b34d36c4215cd8e2bdb3
now trying with timeout 2
now trying with timeout 4
USB read rc read 64
USB recv: 000700090d26925268b80856d002203a19346a43c76b2f8cf6d518877e6832c407c3dd96762bc7877ee6d5f7c8933e3045022100bc8d7e27de620c9b45d5f2c4
now trying with timeout 2
now trying with timeout 4
USB read rc read 64
USB recv: 000700090e95b3b998ac8e02eaacea45e59e4091f7962ee736022024d5d46eb1210d55b79298ef23dbb1ee4b953278cdb8da696ddefcbe491419d09000000000
USB data (len 939): 05040362e82ec73608a3e999113bc5f91d55898ea3672f0690a197c90e9a203c4c5d54ccb641394266cbfa8218b1a2b09212e53abd12c955f07daa318be6daff48e8c028863509071d8f98785ba4bd544b5348ee49a8a6eaaa6cf65f17a35d3eb7922d9a468aec05918bccca65c092113a9465e374c456b16ef93859bc62719483e64a2a5d62a517e8fdf5d7dc8e0a1e1d81dd59023c293d76bdedca8811b830e59d5e1dbb4c9b0e13c78ff672a72529455852539c5a9df6e25ebcd1ba911bbeba477553feb15aeb9394882ede5e5b156fefc0bc3893da3bc195a0a8ab6c93dfb77a6b1577fb533c19dc46182a710435063b40a310918665a1d2ce4e9a85f2f0c95b833082025b30820201a003020102020900a09b1d5d2223b639300a06082a8648ce3d0403023081af310b3009060355040613024b523111300f06035504080c0853656f756c2d53693113301106035504070c0a47616e676e616d2d477531173015060355040a0c0e6557424d20436f2e2c204c74642e31223020060355040b0c1941757468656e74696361746f72204174746573746174696f6e311c301a06035504030c136557424d204341204365727469666963617465311d301b06092a864886f70d010901160e696e666f40652d77626d2e636f6d301e170d3138303732333032303533385a170d3233303732313032303533385a3081b5310b3009060355040613024b523111300f06035504080c0853656f756c2d53693113301106035504070c0a47616e676e616d2d477531173015060355040a0c0e6557424d20436f2e2c204c74642e31223020060355040b0c1941757468656e74696361746f72204174746573746174696f6e3122302006035504030c196557424d204649444f20553246204365727469666963617465311d301b06092a864886f70d010901160e696e666f40652d77626d2e636f6d3059301306072a8648ce3d020106082a8648ce3d0301070342000463b6636e960b27170aa169c1e8e313a7d03562aab90f1bd7787bb625b14df03a7bdd8674ebd73837fa9f00691fbd42476b43b33efdbd945c8372cfa42ef44df8300a06082a8648ce3d0403020348003045022100bfd882289b3f12108849b8fccfa2b34d36c4215cd8e2bdb326925268b80856d002203a19346a43c76b2f8cf6d518877e6832c407c3dd96762bc7877ee6d5f7c8933e3045022100bc8d7e27de620c9b45d5f2c495b3b998ac8e02eaacea45e59e4091f7962ee736022024d5d46eb1210d55b79298ef23dbb1ee4b953278cdb8da696ddefcbe491419d09000
{ "registrationData": "BQQDYuguxzYIo-mZETvF-R1ViY6jZy8GkKGXyQ6aIDxMXVTMtkE5QmbL-oIYsaKwkhLlOr0SyVXwfaoxi-ba_0jowCiGNQkHHY-YeFukvVRLU0juSaim6qps9l8Xo10-t5ItmkaK7AWRi8zKZcCSETqUZeN0xFaxbvk4WbxicZSD5koqXWKlF-j99dfcjgoeHYHdWQI8KT12ve3KiBG4MOWdXh27TJsOE8eP9nKnJSlFWFJTnFqd9uJevNG6kRu-ukd1U_6xWuuTlIgu3l5bFW_vwLw4k9o7wZWgqKtsk9-3emsVd_tTPBncRhgqcQQ1BjtAoxCRhmWh0s5OmoXy8MlbgzCCAlswggIBoAMCAQICCQCgmx1dIiO2OTAKBggqhkjOPQQDAjCBrzELMAkGA1UEBhMCS1IxETAPBgNVBAgMCFNlb3VsLVNpMRMwEQYDVQQHDApHYW5nbmFtLUd1MRcwFQYDVQQKDA5lV0JNIENvLiwgTHRkLjEiMCAGA1UECwwZQXV0aGVudGljYXRvciBBdHRlc3RhdGlvbjEcMBoGA1UEAwwTZVdCTSBDQSBDZXJ0aWZpY2F0ZTEdMBsGCSqGSIb3DQEJARYOaW5mb0BlLXdibS5jb20wHhcNMTgwNzIzMDIwNTM4WhcNMjMwNzIxMDIwNTM4WjCBtTELMAkGA1UEBhMCS1IxETAPBgNVBAgMCFNlb3VsLVNpMRMwEQYDVQQHDApHYW5nbmFtLUd1MRcwFQYDVQQKDA5lV0JNIENvLiwgTHRkLjEiMCAGA1UECwwZQXV0aGVudGljYXRvciBBdHRlc3RhdGlvbjEiMCAGA1UEAwwZZVdCTSBGSURPIFUyRiBDZXJ0aWZpY2F0ZTEdMBsGCSqGSIb3DQEJARYOaW5mb0BlLXdibS5jb20wWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAARjtmNulgsnFwqhacHo4xOn0DViqrkPG9d4e7YlsU3wOnvdhnTr1zg3-p8AaR-9QkdrQ7M-_b2UXINyz6Qu9E34MAoGCCqGSM49BAMCA0gAMEUCIQC_2IIomz8SEIhJuPzPorNNNsQhXNjivbMmklJouAhW0AIgOhk0akPHay-M9tUYh35oMsQHw92WdivHh37m1ffIkz4wRQIhALyNfifeYgybRdXyxJWzuZisjgLqrOpF5Z5AkfeWLuc2AiAk1dRusSENVbeSmO8j27HuS5UyeM242mlt3vy-SRQZ0A", "clientData": "eyAiY2hhbGxlbmdlIjogInJCU1lKVGxsVFpoZW9kbzJjaDJHaTU5UUt2Q01LZVBocURfZmlhX013Tm8iLCAib3JpZ2luIjogInBhbTpcL1wvaGVhcnRvZmdvbGQiLCAidHlwIjogIm5hdmlnYXRvci5pZC5maW5pc2hFbnJvbGxtZW50IiB9" }`

Any help is appreciated.

Thanks
Christoph

**Comment by a-dma** [comment]
does manually trying to get an explicit authentication with `u2f-host -a authenticate ...` also work?

If not would you mind trying building master from source? That uses libfido2 instead of libu2f-server and libu2f-host (the README needs updating but the build process is the same).

**Comment by chrisrot69** [comment]
Hi,

thanks for your reply. I'm new to fido2, please excuse my not-knowlege.
I tried `u2f-host -a authenticate -o pam://heartofgold <challenge>` and also with the full JSON keyhandle as argument, but nothing happens.
I have to ctrl-c to stop u2f-host. Probably I tried the wrong command. Could give me a hint? Its man-page is quite short.

I could also try to build from source.

Thanks
Christoph

**Comment by a-dma** [comment]
no problem.

Try to reproduce the steps described here https://github.com/yubico/libu2f-server#usage
Start with a registration (calling `u2f-server`, using its output in `u2f-host` and pasting the result back to `u2f-server`). This should work since `pamu2fcfg` seems to be working for you.

Once you have that try an authentication (similar flow as before but different parameters). Does that work?

**Comment by chrisrot69** [comment]
Hi,

I tried this. It works until the authenticate-step.
When I paste the output from 
`u2f-server -aauthenticate -ohttp://demo.yubico.com -i http://demo.yubico.com -k keyhandle.dat -p userkey.dat` 
into `u2f-host -d -aauthenticate -o http://demo.yubico.com` I get this error message:

`{ "keyHandle": "nvWi5fUgBgS-a3bJicJOuejODLJuNUfBmLu4kmhEovsZE9iRvwFK0lLF3BewfHwUka0VRNgQaZ_OgYbJUB5XgUkl_f9WKloYR-ZxAPKNJeaePn5TRkBiAT79xwV0Sqq9YzUNMfMiEx9KcSl_Nx1lDmhc12iyxJr7h2LO2MdQ01UDhWnVPUp6xQ2cdVHyezN0xEPZlO1sYzgPnCgKJ7rTIJxfSlcmQbhSg1yMoHxzGVuEMyDIyxBowsWIyBPyrGO6", "version": "U2F_V2", "challenge": "w4wEQD561wz9ufLuQ0bx9aEQN6E1Sz3_-0nX6rM3Nxg", "appId": "http:\/\/demo.yubico.com" }
USB send: 00ffffffff860008a45954cc7613fe74000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
USB write returned 65
now trying with timeout 2
now trying with timeout 4
now trying with timeout 8
USB read rc read 64
USB recv: ffffffff860011a45954cc7613fe740007000c0202086b0d00000000000000000000000000000000000000000000000000000000000000000000000000000000
device /dev/hidraw0 discovered as 'eWBM Security Key(Goldengate G310)'
  version (Interface, Major, Minor, Build): 2, 2, 8, 107  capFlags: 13
JSON: { "keyHandle": "nvWi5fUgBgS-a3bJicJOuejODLJuNUfBmLu4kmhEovsZE9iRvwFK0lLF3BewfHwUka0VRNgQaZ_OgYbJUB5XgUkl_f9WKloYR-ZxAPKNJeaePn5TRkBiAT79xwV0Sqq9YzUNMfMiEx9KcSl_Nx1lDmhc12iyxJr7h2LO2MdQ01UDhWnVPUp6xQ2cdVHyezN0xEPZlO1sYzgPnCgKJ7rTIJxfSlcmQbhSg1yMoHxzGVuEMyDIyxBowsWIyBPyrGO6", "version": "U2F_V2", "challenge": "w4wEQD561wz9ufLuQ0bx9aEQN6E1Sz3_-0nX6rM3Nxg", "appId": "http:\/\/demo.yubico.com" }
JSON challenge URL-B64: w4wEQD561wz9ufLuQ0bx9aEQN6E1Sz3_-0nX6rM3Nxg
client data: { "challenge": "w4wEQD561wz9ufLuQ0bx9aEQN6E1Sz3_-0nX6rM3Nxg", "origin": "http:\/\/demo.yubico.com", "typ": "navigator.id.getAssertion" }
JSON: { "keyHandle": "nvWi5fUgBgS-a3bJicJOuejODLJuNUfBmLu4kmhEovsZE9iRvwFK0lLF3BewfHwUka0VRNgQaZ_OgYbJUB5XgUkl_f9WKloYR-ZxAPKNJeaePn5TRkBiAT79xwV0Sqq9YzUNMfMiEx9KcSl_Nx1lDmhc12iyxJr7h2LO2MdQ01UDhWnVPUp6xQ2cdVHyezN0xEPZlO1sYzgPnCgKJ7rTIJxfSlcmQbhSg1yMoHxzGVuEMyDIyxBowsWIyBPyrGO6", "version": "U2F_V2", "challenge": "w4wEQD561wz9ufLuQ0bx9aEQN6E1Sz3_-0nX6rM3Nxg", "appId": "http:\/\/demo.yubico.com" }
JSON app_id http://demo.yubico.com
JSON: { "keyHandle": "nvWi5fUgBgS-a3bJicJOuejODLJuNUfBmLu4kmhEovsZE9iRvwFK0lLF3BewfHwUka0VRNgQaZ_OgYbJUB5XgUkl_f9WKloYR-ZxAPKNJeaePn5TRkBiAT79xwV0Sqq9YzUNMfMiEx9KcSl_Nx1lDmhc12iyxJr7h2LO2MdQ01UDhWnVPUp6xQ2cdVHyezN0xEPZlO1sYzgPnCgKJ7rTIJxfSlcmQbhSg1yMoHxzGVuEMyDIyxBowsWIyBPyrGO6", "version": "U2F_V2", "challenge": "w4wEQD561wz9ufLuQ0bx9aEQN6E1Sz3_-0nX6rM3Nxg", "appId": "http:\/\/demo.yubico.com" }
JSON keyHandle URL-B64: nvWi5fUgBgS-a3bJicJOuejODLJuNUfBmLu4kmhEovsZE9iRvwFK0lLF3BewfHwUka0VRNgQaZ_OgYbJUB5XgUkl_f9WKloYR-ZxAPKNJeaePn5TRkBiAT79xwV0Sqq9YzUNMfMiEx9KcSl_Nx1lDmhc12iyxJr7h2LO2MdQ01UDhWnVPUp6xQ2cdVHyezN0xEPZlO1sYzgPnCgKJ7rTIJxfSlcmQbhSg1yMoHxzGVuEMyDIyxBowsWIyBPyrGO6
error (-3): error in JSON handling`

**Comment by a-dma** [comment]
I'm not familiar with the device you're using, but it looks like it's only returning 192 whereas U2F expect 256 bytes for the keyHandle.

Does the device behave correctly with https://demo.yubico.com/webauthn-technical/registration? Try doing an authentication after registering.

If so I would try installing libfido2 and building HEAD on master and trying pam-u2f.so again.

**Comment by a-dma** [comment]
Actually the problem seems to be the opposite, too much data rather than too little. There is an internal buffer in u2f-host that decodes up to 255 bytes of Base64 data and the encoded keyHandle sent by the device is 256 bytes of Base64 data.

The advice is still the same though. Try with the demo website and/or with HEAD on master.

**Comment by chrisrot69** [comment]
Hi,

I tested the website. I can register and authenticate. Next I'll try building HEAD.
Thanks for your help.

**Comment by a-dma** [comment]
Thank you for following along. Let me know how that goes.

**Comment by a-dma** [comment]
I'm not familiar with your particular device, but it looks like pam_u2f is succeeding.

Are you sure you're being asked for the PIN of the device and not the sudo password?

**Comment by chrisrot69** [comment]
Hi,

yes, you are right. I had a mistake in the pam.d/sudo-i configuration file.

Now it works.
Thanks for your help. I think we can close this bug.

**Comment by a-dma** [comment]
Great, glad it works :)
