### ISSUE TITLE
libpam-u2f Ubuntu release outdated

### ISSUE THREAD

**Issue by plygrnd** [Yubico/pam-u2f#150]
Per [Canonical's Universe listing](https://packages.ubuntu.com/focal/libpam-u2f), the last release available for Ubuntu is `1.0.8-1`. This breaks folks with newer Yubikeys - we should release `1.1.9` to Ubuntu users ASAP.

**Comment by plygrnd** [comment]
Reported to Canonical as well in [bug 1888955](https://bugs.launchpad.net/ubuntu/+source/pam-u2f/+bug/1888955)

**Comment by a-dma** [comment]
I see you wrote that the canonical bug can be closed. Is this the case for this issue as well? Have you resolved your problem?

**Comment by plygrnd** [comment]
Yes, this can be closed. I was using a FIPS Yubikey - these don't appear to answer challenges correctly - but it was my mistake.
