### ISSUE TITLE
Individual authorization file cannot be read when login on console

### ISSUE THREAD

**Issue by dlippold** [Yubico/pam-u2f#152]
I use pam_u2f version 1.0.8 on a Fedora LXDE 32 system. I have added the following line (by using authselect, https://github.com/authselect/authselect) to files in /etc/pam.d/ to require 2-factor authorization:
`
/etc/pam.d/password-auth:auth   required   pam_u2f.so cue nouserok
`

In most cases (e.g. login by lxdm) this works. But when I login on the console the Yubikey is not necessary and I can login by using only the password. That can be a security problem when someone uses a weak password because of the second factor (a weak password would be ok if the 2-factor authorization would really work).

When I add "debug" to the line above I get the attached output. The important lines seem to be: 

> debug(pam_u2f): pam-u2f.c:265 (pam_sm_authenticate): Using authentication file /home/anonym/.config/Yubico/u2f_keys
> debug(pam_u2f): pam-u2f.c:278 (pam_sm_authenticate): Dropping privileges
> debug(pam_u2f): pam-u2f.c:284 (pam_sm_authenticate): Switched to uid 1001
> debug(pam_u2f): util.c:42 (get_devices_from_authfile): Cannot open file: /home/anonym/.config/Yubico/u2f_keys (Permission denied)
> debug(pam_u2f): pam-u2f.c:295 (pam_sm_authenticate): Restored privileges
> debug(pam_u2f): pam-u2f.c:306 (pam_sm_authenticate): Found no devices but nouserok specified. Skipping authentication

The problem seems to be that pam_u2f cannot read the file "$HOME/.config/Yubico/u2f_keys".

Steps to reproduce that (tested with Fedora LXDE 32):

1. Add the above line to the files in /etc/pam-d/ (e.g. execute "authselect select sssd with-pam-u2f-2fa without-nullok" by root)
2. Activate a Yubikey for a user (e.g. exectute "mkdir ~/.config/Yubico; pamu2fcfg > ~/.config/Yubico/u2f_keys" by the user and press the Yubikey button)
3. Reboot the system
4. Wait until the login manager appears
5. Press the key combination Strg-Alt-F2 to switch to a console
6. Login as the user only with the password without the Yubikey

[pam_u2f-debug-output.txt](https://github.com/Yubico/pam-u2f/files/5019295/pam_u2f-debug-output.txt)

**Comment by a-dma** [comment]
What are the permissions of and who owns the file `~/.config/Yubico/u2f_keys`? Is it user 1001 or somebody else?

**Comment by dlippold** [comment]
The owner of the file `~/.config/Yubico/u2f_keys` is user 1001, the permissions are 664. The primary group of user 1001 is a group which only contains this user.

But on the system SELinux is activated (it is activated by default on Fedora 32). When I disable SELinux the authentication works fine, i.e. the Yubikey is also needed for login on the console. The attached file "pam_u2f-debug-user-noSELinux.txt" contains the debug output for that case (I replaced some text by "[text deleted]").

I further tested the usage of a central authorization file by adding "authfile=/etc/u2f_mappings" to the line in the pam files. With SELinux activated the effect is the same as with a user mapping file (login is possible without Yubikey on the console). The file "pam_u2f-debug-central-withSELinux.txt" contains the debug output for that case.

After disabling SELinux the authentication works fine again also with a central authorization file (i.e. the Yubikey is needed for login on the console).

It seems to me that additional SELinux rules are needed when SELinux is activated.

[pam_u2f-debug-user-noSELinux.txt](https://github.com/Yubico/pam-u2f/files/5024271/pam_u2f-debug-user-noSELinux.txt)

[pam_u2f-debug-central-withSELinux.txt](https://github.com/Yubico/pam-u2f/files/5024272/pam_u2f-debug-central-withSELinux.txt)

**Comment by a-dma** [comment]
It looks like everything is working as it should to me and that SELinux is causing issues.

I don't use SELinux, but is it possible that the permission denied error is because of something being incorrect with the security context? Running something like `ls -lZ ~/.config/Yubico/u2f_keys` can maybe shed some light?
Otherwise have a look at `/var/log/audit/audit.log`.

**Comment by dlippold** [comment]
The result of `ls -lZ ~/.config/Yubico/u2f_keys` is:

> -rw-rw-r--. 1 anonym anonym unconfined_u:object_r:config_home_t:s0 224 25. Jul 22:01 .config/Yubico/u2f_keys

I attached the difference of the file `/var/log/audit/audit.log` generated by the login on the console without the Yubikey in the file `audit-diff.txt`. The important line seems to be:

> type=AVC msg=audit(1596650203.671:296): avc:  denied  { read } for  pid=2036 comm="login" name="u2f_keys" dev="sda2" ino=655371 scontext=system_u:system_r:local_login_t:s0-s0:c0.c1023 tcontext=unconfined_u:object_r:config_home_t:s0 tclass=file permissive=0

In my last comment I wrote that the problem also occurs with a central authorization file. That statement was wrong (I made a mistake at the test). The problem seems to occur only with an individual authorization file (in `~/.config/Yubico/u2f_keys`).

[audit-diff.txt](https://github.com/Yubico/pam-u2f/files/5030698/audit-diff.txt)

**Comment by a-dma** [comment]
Again, I'm not an expert on SELinux, but it looks like there is a mismatch on the labels, possibly `chcon` can help there?
I think this could be a good place to start https://docs.fedoraproject.org/en-US/quick-docs/troubleshooting_selinux/, especially https://fedorapeople.org/~dwalsh/SELinux/Presentations/selinux_four_things.pdf.

**Comment by dlippold** [comment]
Thanks for the links about SELinux. There is a reference to the SELinux mailing list (https://lists.fedoraproject.org/admin/lists/selinux.lists.fedoraproject.org/). So I sent a mail to the mailing list about this problem.

**Comment by dlippold** [comment]
The issue was further discussed on https://bugzilla.redhat.com/show_bug.cgi?id=1860888 . It became clear that the SELinux rules have to be updated. Currently only files in `~/.yubico/` and in `/root/.yubico/` can be read by the login process (in particular not the default files `~/.config/Yubico/u2f_keys`). Therefore I suggested to allow the login process to read all files in the home directory because every file in a home directory can be used as an argument for the parameter `authfile` of pam-u2f. But it may be advantageous for SELinux to restict the possible files which can be read by the login process.

Would it be sufficent to allow only files in `~/.config/Yubico/` or more general in `~/.config/u2f/` as value for the parameter `authfile`? Then SELinux could restrict the readability to that directory.

BTW: How can I specify the existing file `~/.yubico/u2f_keys` as the mapping file? What has to be the value for the parameter "authfile"? On https://developers.yubico.com/pam-u2f/#files there is stated (in section "Individual authorization mapping by user"):

> You may want to specify a different per user file (relative to the users’ home dir), i.e. .ssh/u2f_keys.

But if I use `authfile=.yubico/u2f_keys` I get the following debug output:

> debug(pam_u2f): pam-u2f.c:221 (pam_sm_authenticate): Found user anonym
> debug(pam_u2f): pam-u2f.c:222 (pam_sm_authenticate): Home directory for anonym is /home/anonym
> debug(pam_u2f): pam-u2f.c:271 (pam_sm_authenticate): Using authentication file .yubico/u2f_keys
> debug(pam_u2f): util.c:42 (get_devices_from_authfile): Cannot open file: .yubico/u2f_keys (No such file or directory)

I think it would be useful to output the full path of the file in line 42 of "util.c".

**Comment by a-dma** [comment]
Thanks for the update. It should be enough to allow things in `~/.config/Yubico` to be accessible. If a user wants to put the authentication file in a different place then maybe they can modify SELinux rules themselves as well at that point?

On the other hand if having the whole home directory readable is not a big issue then it would make things easier.

**Comment by a-dma** [comment]
It appears Bug 1860888 has been resolved and closed.

**Comment by dlippold** [comment]
Unfortunately the bug is not fully resolved. Its is only resolved for new users of pam-u2f but not for systems with SELinux who already use pam-u2f. I made a suggestion on https://bugzilla.redhat.com/show_bug.cgi?id=1860888 how the bug can easily resolved also for those systems (see comment 24 and 25) and also send a corresponding mail directly to the RedHat security team but didn't get an answer. Therefore I suspect (and didn't understand the reasons for that) that the bug will not be resolved anymore for systems who already use pam-u2f.

Would it be possible to add a hint to the man page (or to inform the users of pam-u2f in another way) that on every system with SELinux where pam-u2f is already used the following command has to be executed? `fixfiles /root/.config/Yubico/ /home/*/.config/Yubico/`

Furthermore on _all_ systems with SELinux (also on those on which pam-u2f is newly installed) the command `fixfile` has to be applied to a file which is given as an argument to the parameter `authfile` of pam-u2f.

For the future it would very useful if a mail could be sent to the SELinux mailing list (https://lists.fedoraproject.org/admin/lists/selinux.lists.fedoraproject.org/) when a new configuration file or directory (something like `~/.config/Yubico/`) is added to pam-u2f.

**Comment by a-dma** [comment]
Thanks for the additional information. I've added some text in the documentation, mentioned above.
Does it make sense? Do you think it's enough?

**Comment by dlippold** [comment]
From my point of view the added text contains the important information for users of SELinux. But I have some smaller remarks and suggestions.  In the following I refer to the lines in the README file.

- Line 330: Please replace "Red Hat Linux" by "Fedora Linux" (the community version of Red Hat Linux, i.e. RHEL) because Red Hat Linux (RHEL) currently does not contain a rpm package `pam-u2f`.

- Line 331: The issues not only affect Linux systems for which SELinux is enable by default but also those systems for which SELinux was enabled later. So I suggest to replace "that enable SELinux by default" by "which contain SELinux".

- Line 334: I suggest to add "without using the Yubikey" to the end of the sentence.

- Line 339: The `chcon` command is only necessary for authfiles and for directories with authfiles defined by root, not for the default authfiles and directories (i.e. `/root/.config/Yubico/` and `/home/*/.config/Yubico/`). Therefore I suggest to replace "to an authfile the command" by "to an authfile or directory defined by root the command".

- Line 343: The `chcon` command can also be applied to an directory similar to `~/.config/Yubico/` (`-R` stands for _recursively_). Therefore I suggest to replace "/path/to/authfile" by "/path/to/authfile_or_directory".

**Comment by a-dma** [comment]
Thanks, I've updated the wording. Please let me know what you think.

**Comment by dlippold** [comment]
That is excellent and complete from my point of view.

**Comment by a-dma** [comment]
Great thanks. I'll merge it in.
