### ISSUE TITLE
make check failed with core dump

### ISSUE THREAD

**Issue by NgoHuy** [Yubico/pam-u2f#155]
Hi team,

I built pam-u2f today, when using `make check` the error looks like:
```
debug(pam_u2f): util.c:959 (get_devices_from_authfile): The owner of the authentication file is neither  nor root
get_devices: get_devices.c:39: main: Assertion `rc == 1' failed.
/bin/sh: line 5: 279250 Aborted                 (core dumped) ${dir}$tst
```
I see the update from yesterday causing the bug.

**Comment by a-dma** [comment]
Right, I'm not sure how to really fix that. The module expects the right set of privileges/permissions on the files and that means that the file has to be owned by root in this case (or a hypothetical user called `myuser`).

It would be possible to interactively get the correct user (i.e., the one who ran the test) and use that instead, but at that point all the authfiles would be incorrect and the tests would still fail.

Running `sudo chown root:root tests/credentials/*` will fix the tests and that's what the CI does.
Unfortunately I don't have a better solution other than adding a more useful message to that error.

**Comment by NgoHuy** [comment]
the code hardcode `myuser` as user for the tests. For current user, they must regenerate tests/credentials/* or change `myuser` to current user.
I created the patch for setting username in get_devices.c

**Comment by a-dma** [comment]
But with this change you would still have to regenerate all the credentials. How is that different from changing ownership of the ones that already exist? Regenerating is quite tedious since it requires touching the device a whole bunch of times.

**Comment by NgoHuy** [comment]
> But with this change you would still have to regenerate all the credentials. How is that different from changing ownership of the ones that already exist? Regenerating is quite tedious since it requires touching the device a whole bunch of times.

they only need `sed -i 's/myuser/[your-user-name]/g' ` after using my patch.

**Comment by a-dma** [comment]
I understand, but it's still a command that has to be run in order for the tests to pass. Does it matter if that command is `sed` or `chown`? The only difference I can see is that it one doesn't require sudo.

**Comment by NgoHuy** [comment]
sudo will prevent user from changing the file as edit, delete or regenerate credentials. We should prevent using privileged user.

**Comment by NgoHuy** [comment]
I confirm that running ./configure will generate credentials as user, not require run sed or sudo again.

**Comment by a-dma** [comment]
I feel I need to think about this a bit more. I tried a similar solution before and I wasn't happy with it, I still think it's more of a workaround than an actual solution given that it still requires doing "something" after cloning the repository in order for the tests to be run.

At the same time I can agree that not having to `chown` files to root and not requiring `sudo` is better than having to update a bunch of files. However, those files are checked in and modifying them would mean having to keep a useless diff around.

Maybe the solution is to not ship pregenerated credentials but rather to add a step to `make check` that regenerates the credentials for the current user on-the-fly if they're not there.

**Comment by NgoHuy** [comment]
just add step replace with current user step to `make check` is better than regenerates the credentials. Because it requires user multiple time `typing pin and touch`

**Comment by a-dma** [comment]
I've pushed a bunch of changes to the `fix_tests` branch (fed5f4b3a8d8ed767e8bb5f3d8644cfdb515e3c7). It looks like this is passing on Travis, but if you could run it on your end and confirm it would be great.

Ideally you shouldn't need to do anything just pull and `make check`.

**Comment by NgoHuy** [comment]
The fix is fine. But regenerate.py did not work, I patched it on https://github.com/Yubico/pam-u2f/pull/156, please review

**Comment by a-dma** [comment]
What part didn't work? I don't think I agree with that patch.
The idea is for `regenerate_credentials.py` to create a bunch of .templ files that are then converted into .cred files when running `make check` (and the necessary C code to test them).

Nobody should be running that script unless the test cases need updating.
