### ISSUE TITLE
nodetect option started causing inability to authenticate in pam

### ISSUE THREAD

**Issue by ethician** [Yubico/pam-u2f#161]
After upgrading pam-u2f from 1.0.8-3 -> 1.1.0-1 on Arch and having the following `system-auth` config line

    auth      required  pam_unix.so     try_first_pass nullok
    auth      required  pam_u2f.so      authfile=/etc/u2f_mappings nodetect

having `nodetect` is no longer viable as my Yubikey 5 NFC is no longer recognized during authentication. The Y doesn't even start flashing after a password is entered.

When `nodetect` is removed all gets back to normal and starts working as before.

If this is the intended behaviour of version `1.1.0` please elaborate further on possible downsides of not having `nodetect` enabled (leakage, etc.).

**Comment by a-dma** [comment]
I believe that is a bug. Are you able to try abfefa8c32c6f440d0002828aa0b22f86866adcc out and see if it fixes the problem?

**Comment by ethician** [comment]
Yes, that fixed it! Thanks!

**Comment by a-dma** [comment]
Glad to hear, thank you for helping.
I'll merge that in.
