### ISSUE TITLE
Yubikey Touch U2F Security Key PIN

### ISSUE THREAD

**Issue by elegos** [Yubico/pam-u2f#167]
Hello!

I'm trying to enable U2F login with my Security Key on Fedora. I've compiled the library and installed it, configured the PAM login configuration, but when I try to run the `pamu2fcfg` command, it asks me for a PIN (which I never had...).

What can I do? Is it compatible with the key I have?

This is the line of `lsusb`

```
Bus 001 Device 015: ID 1050:0120 Yubico.com Yubikey Touch U2F Security Key
```

Thanks

**Comment by a-dma** [comment]
Hi, what version of pam-u2f are you running? How are you invoking `pamu2fcfg`? Finally, what is in the module's configuration file?

Both `pamu2fcfg` and the module itself can be configured to ask for a PIN, but that will only work if your device has support for it.

**Comment by elegos** [comment]
Hello @a-dma 

I'm running pam-u2f (master branch), compiled by myself (there is no pam-u2f module in the fedora repositories). `pamu2fcfg` is being called as follows: `pamu2fcfg -opam://${HOSTNAME} -ipam://${HOSTNAME}`

I think I've resolved the issue though: I once used the U2F key on Windows and it asked me to set a PIN. I thought it was unrelated (Windows-side), but trying the same PIN worked out. I'm now wondering what would happen if I'd restore the key (always via Windows functionality). I've secured lots of accounts with this key, I don't know if doing the factory restore would change the key 'signature' aka making it useless against the old-associated keys.

P.S.
Also I have no PUK and I read that if I write a wrong PIN 3 times, it locks and asks for the PUK, after which the device will lock...

Thanks :)

**Comment by a-dma** [comment]
I see. It sounds like Windows did set a PIN for you. If you want to be 100% sure you can install YubiKey Manager and run `ykman fido info`.

There is no "unset PIN" in FIDO, the only way to achieve that is to reset the device, but as you suspected that **will** invalidate all the previous credentials.

Likewise, I'm not aware of any PUK, it might be something that Windows constructs for your and uses as part of their recovery mechanism.

That being said, you should still be able to do an authentication without PIN verification.

**Comment by elegos** [comment]
`PIN is set, with 8 tries left.`
Bad, bad Windows!

Does the counter reset when I enter the right PIN btw? And yes, the authentication is done PIN-less (fortunately).

Thanks :)

**Comment by a-dma** [comment]
Yes, the counter is reset, you also have three attempts per session, where a session starts when the device is powered up, so you can't use up all eight attempts at once.

**Comment by a-dma** [comment]
It is used for user verification, and is reported as part of the assertion statement. It can be used by the Relying Party to make decisions on whether or not to accept such a statement.

I'll close the issue since it looks like the main problem was resolved.
