### ISSUE TITLE
When building on fedora JSON and Check packages are not found.

### ISSUE THREAD

**Issue by gr0undzer0** [Yubico/pam-u2f#17]
pam-u2f, 
  When building pam_u2f on Fedora22 I get No package 'json' found or No package 'check' found. I tried setting the LIBJSON_LIBS LIBJSON_CFLAGS CHECK_LIBS and CHECK_CFLAGS to /usr/lib/<appropriate.so> . I got through the build but then make failed saying it couldn't find json.h.  

json-c , json-glib, json-devel are all installed
check and check-devel are installed as well. 

Any help would be much appreciated!!

**Comment by gr0undzer0** [comment]
This is actually when building the prerequisit libu2f-host and libu2f-server libraries so feel free to close if you'd like me to move the question to one of them. Thanks!

**Comment by a-dma** [comment]
I don't have an install of F22 handy, but I've tried on F21.

It seems that on Fedora *check* doesn't use pkg-config. Anyway, that shouldn't be a big deal since check is only used to run self tests. If you just call `make` instead of `make check` you should have no problems.

For *libjson*, that seems to be working ok on my install. Do you see an output to `pkg-config json-c --cflags --libs` ?

You can always try to create .pc files for both packages yourself, just make sure the files are actually there i.e., the packages are installed correctly.

**Comment by mikejonesey** [comment]
I had issues on centos, had to locate pc files and export package config
path

**Comment by a-dma** [comment]
I know these things are annoying, but there isn't much we can do about them. Maybe it's a good idea to try and reach out to the developers/maintainers of the software/packages to see whether they can add support.

**Comment by gr0undzer0** [comment]
Thank you for your responses. I created a json.pc file that looks like this : 
prefix=/usr
exec_prefix=/usr
libdir=/usr/lib
 name: Json
Description: Json library 
Version: 2.0.1


./configure works but when I run make I still get : 
core.c:39:18 fatal error: json.h: No such file or directory compilatin terminated. 

I searched around for json.h and found it under a different package jsoncpp. It's located under /usr/include/jsoncpp/json/json.h. Is there a way to tell ./configure or make where this is ? 

Thanks again for any help or advice.

**Comment by a-dma** [comment]
are you sure you have the right package?
It seems as if you've installed jsoncpp which is not what you need.

The package you have to install is https://admin.fedoraproject.org/pkgdb/package/json-c/

**Comment by gr0undzer0** [comment]
So i did't have the -devel json.c package installed. Once In installed that i had better luck. I still had to set the library direcotryes with the _LIBS and _CFLAGS flags but I got through the builds of both _host and _server. Then I installed pam_u2f ... now when I try to use the pamu2fcfg command it still cant find the libu2f-host.so.0 library. But I'm looking right at it in /usr/local/lib.

**Comment by a-dma** [comment]
Once you build and install both libu2f-server and libu2f-host, a u2f-{server,host}.pc file gets installed as well.

Find out where those files are in your system (should be /usr/local/lib/pkgconfig) and then export that path as PKG_CONFIG_PATH.

Once you have the variable set, try rebuilding pam-u2f.

**Comment by gr0undzer0** [comment]
One step closer but now im seeing this in the debug. I'm sorry to have you guys troubleshoot this but in return I'll write something up for fedora and post it where you like. I'm really close : 

 su - gr0undzer0
[pam-u2f.c:parse_cfg(47)] called.
[pam-u2f.c:parse_cfg(48)] flags 0 argc 2
[pam-u2f.c:parse_cfg(50)] argv[0]=authfile=/etc/u2f_mappings
[pam-u2f.c:parse_cfg(50)] argv[1]=debug
[pam-u2f.c:parse_cfg(51)] max_devices=0
[pam-u2f.c:parse_cfg(52)] debug=1
[pam-u2f.c:parse_cfg(53)] interactive=0
[pam-u2f.c:parse_cfg(54)] cue=0
[pam-u2f.c:parse_cfg(55)] manual=0
[pam-u2f.c:parse_cfg(56)] nouserok=0
[pam-u2f.c:parse_cfg(57)] alwaysok=0
[pam-u2f.c:parse_cfg(58)] authfile=/etc/u2f_mappings
[pam-u2f.c:parse_cfg(59)] origin=(null)
[pam-u2f.c:parse_cfg(60)] appid=(null)
[pam-u2f.c:pam_sm_authenticate(102)] Origin not specified, using "pam://Aiolos"
[pam-u2f.c:pam_sm_authenticate(113)] Appid not specified, using the same value of origin (pam://Aiolos)
[pam-u2f.c:pam_sm_authenticate(123)] Maximum devices number not set. Using default (24)
[pam-u2f.c:pam_sm_authenticate(139)] Requesting authentication for user gr0undzer0
[pam-u2f.c:pam_sm_authenticate(150)] Found user gr0undzer0
[pam-u2f.c:pam_sm_authenticate(151)] Home directory for gr0undzer0 is /home/gr0undzer0
[pam-u2f.c:pam_sm_authenticate(202)] Using authentication file /etc/u2f_mappings
[util.c:get_devices_from_authfile(80)] Authorization line: gr0undzer0:xxxxxxx,xxxxxxxxx
[util.c:get_devices_from_authfile(85)] Matched user: gr0undzer0
[util.c:get_devices_from_authfile(113)] KeyHandle for device number 1: xxxxxxxxxxx
[util.c:get_devices_from_authfile(140)] publicKey for device number 1: xxxxxxxxxx
[util.c:get_devices_from_authfile(155)] Length of key number 1 is 57
[util.c:get_devices_from_authfile(183)] Found 1 device(s) for user gr0undzer0
[util.c:do_authentication(243)] Device max index is 0
[util.c:do_authentication(266)] Attempting authentication with device number 1
[util.c:do_authentication(274)] Unable to set publicKey Crypto error
[pam-u2f.c:pam_sm_authenticate(237)] do_authentication returned -2
[pam-u2f.c:pam_sm_authenticate(251)] done. [Authentication failure]

**Comment by a-dma** [comment]
[util.c:get_devices_from_authfile(155)] Length of key number 1 is 57

that looks weird. The length of the public key should be 65. Make sure you haven't missed any character from the output of pamu2fcfg.
You can run it as `# pamu2cfg > /etc/u2f_mappings`

**Comment by gr0undzer0** [comment]
faceToDesk: I must have had a bad copy earlier. Thanks so much! Auth is working now.

**Comment by a-dma** [comment]
I'm glad you got this going. Happy to help.
