### ISSUE TITLE
Configuration for RHEL

### ISSUE THREAD

**Issue by andersonreloaded** [Yubico/pam-u2f#173]
Hi Folks,

Having tested Yukikey on Ubuntu 18.04, I am attempting to use Yubikey 5 NFC on RHEL 7.8.
Have build necessary tools including `libcbor`, `libfido2` and `pam-u2f` from source code.
To start with, I would like to test by configuring `/etc/pam.d/sudo` file.
However, the default configuration of the file is different for Ubuntu and RHEL. 

For Ubuntu the configuration is as follows:

```
session    required   pam_env.so readenv=1 user_readenv=0
session    required   pam_env.so readenv=1 envfile=/etc/default/locale user_readenv=0
@include common-auth
auth       required  pam_u2f.so authfile=/etc/security/u2f_keys debug debug_file=/var/log/pam_u2f.log
@include common-account 
@include common-session-noninteractive
```

Default configuration for RHEL is as follows:
```
auth       include      system-auth
account    include      system-auth
password   include      system-auth
session    optional     pam_keyinit.so revoke
session    include      system-auth

```

Let me know if anyone has configured RHEL for `sudo`, `sshd` and `gdm login` using Yubikey.

**Comment by LDVG** [comment]
Hi,

Without knowing exactly what your end goal is, the below _should_ give you a similar experience to your Ubuntu configuration. 

```
auth       substack     system-auth
auth       required     pam_u2f.so authfile=/etc/security/u2f_keys debug debug_file=/var/log/pam_u2f.log
account    include      system-auth
password   include      system-auth
session    optional     pam_keyinit.so revoke
session    include      system-auth
``` 
or

```
auth       required     pam_u2f.so authfile=/etc/security/u2f_keys debug debug_file=/var/log/pam_u2f.log
auth       include      system-auth
account    include      system-auth
password   include      system-auth
session    optional     pam_keyinit.so revoke
session    include      system-auth
``` 

depending on your preferences. Keep a root session open while checking the results from another user on another console to prevent locking yourself out when experimenting with the settings.

**Comment by andersonreloaded** [comment]
@LDVG Thank you for responding.

The aim is to implement two-factor user authentication using PAM.
The default configuration for both the operating system was different, so I thought of seeking help.
Shall go through PAM documentation for understanding each line mentioned in the default configuration.

The final goal is to implement three-factor user authentication using PAM including biometric authentication.

**Comment by LDVG** [comment]
Hi,

Sounds like example configurations above should be a good starting point for your setup. As for reading material, I recommend the man pages for `pam.d(5)`. You may also want to read [RedHat's guide on system-level authentication](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/system-level_authentication_guide/index), which also has a chapter about PAM (chapter 10). :slightly_smiling_face:

**Comment by andersonreloaded** [comment]
@LDVG Thank you for pointing to the RHEL documentation!
I just started getting the hang of PAM :-) and it's a long way to go.
