### ISSUE TITLE
Is not working with Fedora 34

### ISSUE THREAD

**Issue by perceival** [Yubico/pam-u2f#178]
Version 1.1.1 worked fine with Fedora 33 however is no longer working with Fedora 34 regardless whether that is upgrade or fresh install.
Moreover after make uninstall pam-u2f is still not authenticating despite being reported as 1.0.8 version.

**Comment by LDVG** [comment]
Hi,

We just released 1.1.1, I recommend updating. If you're still having issues, could you post a debug log?

**Comment by perceival** [comment]
Looks like it's still not working. Debug log:
`debug(pam_u2f): pam-u2f.c:284 (pam_sm_authenticate): Switched to uid 1000
debug(pam_u2f): util.c:105 (get_devices_from_authfile): Authorization line: user:/redacted/==,/redacted/==,es256,+presence+pin
debug(pam_u2f): util.c:110 (get_devices_from_authfile): Matched user: user
debug(pam_u2f): util.c:137 (get_devices_from_authfile): KeyHandle for device number 1: /redacted/==
debug(pam_u2f): util.c:156 (get_devices_from_authfile): publicKey for device number 1: /redacted/==,es256,+presence+pin
debug(pam_u2f): util.c:167 (get_devices_from_authfile): Length of key number 1 is 54
debug(pam_u2f): util.c:182 (get_devices_from_authfile): Invalid hex number in key
debug(pam_u2f): pam-u2f.c:295 (pam_sm_authenticate): Restored privileges
debug(pam_u2f): pam-u2f.c:310 (pam_sm_authenticate): Unable to get devices from file /home/user/.config/Yubico/u2f_keys
debug(pam_u2f): pam-u2f.c:410 (pam_sm_authenticate): done. [Authentication service cannot retrieve authentication info]
debug(pam_u2f): pam-u2f.c:99 (parse_cfg): called.
debug(pam_u2f): pam-u2f.c:100 (parse_cfg): flags 32768 argc 4
debug(pam_u2f): pam-u2f.c:102 (parse_cfg): argv[0]=cue
debug(pam_u2f): pam-u2f.c:102 (parse_cfg): argv[1]=pinverification=1
debug(pam_u2f): pam-u2f.c:102 (parse_cfg): argv[2]=debug
debug(pam_u2f): pam-u2f.c:102 (parse_cfg): argv[3]=debug_file=/var/log/pam_u2f.log
debug(pam_u2f): pam-u2f.c:104 (parse_cfg): max_devices=0
debug(pam_u2f): pam-u2f.c:105 (parse_cfg): debug=1
debug(pam_u2f): pam-u2f.c:106 (parse_cfg): interactive=0
debug(pam_u2f): pam-u2f.c:107 (parse_cfg): cue=1
debug(pam_u2f): pam-u2f.c:108 (parse_cfg): nodetect=0
debug(pam_u2f): pam-u2f.c:109 (parse_cfg): manual=0
debug(pam_u2f): pam-u2f.c:110 (parse_cfg): nouserok=0
debug(pam_u2f): pam-u2f.c:111 (parse_cfg): openasuser=0
debug(pam_u2f): pam-u2f.c:112 (parse_cfg): alwaysok=0
debug(pam_u2f): pam-u2f.c:113 (parse_cfg): authfile=(null)
debug(pam_u2f): pam-u2f.c:114 (parse_cfg): authpending_file=(null)
debug(pam_u2f): pam-u2f.c:115 (parse_cfg): origin=(null)
debug(pam_u2f): pam-u2f.c:116 (parse_cfg): appid=(null)
debug(pam_u2f): pam-u2f.c:117 (parse_cfg): prompt=(null)
debug(pam_u2f): pam-u2f.c:169 (pam_sm_authenticate): Origin not specified, using "pam://host"
debug(pam_u2f): pam-u2f.c:180 (pam_sm_authenticate): Appid not specified, using the same value of origin (pam://host)
debug(pam_u2f): pam-u2f.c:192 (pam_sm_authenticate): Maximum devices number not set. Using default (24)
debug(pam_u2f): pam-u2f.c:210 (pam_sm_authenticate): Requesting authentication for user user
debug(pam_u2f): pam-u2f.c:221 (pam_sm_authenticate): Found user user
debug(pam_u2f): pam-u2f.c:222 (pam_sm_authenticate): Home directory for user is /home/user
debug(pam_u2f): pam-u2f.c:228 (pam_sm_authenticate): Variable XDG_CONFIG_HOME is not set. Using default value ($HOME/.config/)
debug(pam_u2f): pam-u2f.c:265 (pam_sm_authenticate): Using authentication file /home/user/.config/Yubico/u2f_keys
debug(pam_u2f): pam-u2f.c:278 (pam_sm_authenticate): Dropping privileges
debug(pam_u2f): pam-u2f.c:284 (pam_sm_authenticate): Switched to uid 1000
debug(pam_u2f): util.c:105 (get_devices_from_authfile): Authorization line: user:/redacted/==,/redacted/==,es256,+presence+pin
debug(pam_u2f): util.c:110 (get_devices_from_authfile): Matched user: user
debug(pam_u2f): util.c:137 (get_devices_from_authfile): KeyHandle for device number 1: /redacted/==
debug(pam_u2f): util.c:156 (get_devices_from_authfile): publicKey for device number 1: /redacted/==,es256,+presence+pin
debug(pam_u2f): util.c:167 (get_devices_from_authfile): Length of key number 1 is 54
debug(pam_u2f): util.c:182 (get_devices_from_authfile): Invalid hex number in key
debug(pam_u2f): pam-u2f.c:295 (pam_sm_authenticate): Restored privileges
debug(pam_u2f): pam-u2f.c:310 (pam_sm_authenticate): Unable to get devices from file /home/user/.config/Yubico/u2f_keys
debug(pam_u2f): pam-u2f.c:410 (pam_sm_authenticate): done. [Authentication service cannot retrieve authentication info]
`

**Comment by LDVG** [comment]
Given the following line in your debug log

```
debug(pam_u2f): util.c:182 (get_devices_from_authfile): Invalid hex number in key
```

it would seem to me like you are still running version 1.0.8 (this log message is not present in 1.1.1). 

If you're installing from source, please make sure that you do not have any conflicting version of `pam-u2f` installed via your package manager and that the `pam-u2f` module is installed to the correct location on your system (which can be set via `--with-pam-dir=DIR` when calling `./configure`).

Another Fedora user recently had similar issues (#179) which might be helpful to skim through.

**Comment by perceival** [comment]
Thank you for hint provided. Following command is solving the issue:
./configure --with-pam-dir=/usr/lib64/security
