### ISSUE TITLE
64bit rpms for fedora 22

### ISSUE THREAD

**Issue by gr0undzer0** [Yubico/pam-u2f#18]
Hi pam_u2f team,
     I've built rpm's for pam_u2f, libu2f-host, and libu2f-server. Is there somewhere i could post these so they can be made available to everyone? 

Also,
   Is there anyway to get u2f working over ssh. As in add pam_u2f to the sshd pam config and respond to the challenge from my local laptop? I saw that a patch went into open ssl to support this. I've tried but with no luck.

**Comment by a-dma** [comment]
Thanks for the effort. Generally support other distribution has been a bit complicated. We do it for Debian with a dedicated repo that we know we keep up to date, but it's hard to have the same for external contribution. If you can find a place where to host them I can put a link in the README file, but my best suggestion would be to get them into Fedora in the official way.

Regarding the second question, the OpenSSL patch is unrelated to this (unless there has been more work that I'm not aware of). On way of using ssh is with the manual option where you can copy/past the JSON blobs yourself.

**Comment by spartacus06** [comment]
@gr0undzer0 I've created a Copr project for the U2F libs and PAM module.

https://copr.fedoraproject.org/coprs/spartacus06/yubikey-utils/

Looking to get it in the upstream repos soon.  Need to run fedora-review on the packages and open a package review request.

**Comment by dm8tbr** [comment]
Another approach could be for upstream to use OBS (open build service). It is capable of building in parallel packages for many distributions and multiple package types.
I'm using that successfully to provide up to date builds of Icecast releases for many distributions. https://build.opensuse.org/project/repositories/multimedia:xiph
It also eases exchange between distribution package maintainers and upstream (me) and improvements tend to flow both ways.

**Comment by a-dma** [comment]
That sounds interesting.
Thanks for the pointer I'll look into it.

**Comment by divad** [comment]
Many thanks for building these (and for the patches in the pam-u2f SRPM) - I have managed to get pam-u2f compiled on RHEL7 :-)

**Comment by gsauthof** [comment]
In the meantime a packaging request for Fedora has been approved:

https://bugzilla.redhat.com/show_bug.cgi?id=1283296

**Comment by a-dma** [comment]
Sounds good!
Closing this for now. Feel free to reopen if needed.
