### ISSUE TITLE
authfile parameter documentation is outdated

### ISSUE THREAD

**Issue by perceival** [Yubico/pam-u2f#182]
Since most likely previous version while authfile parameter is being parsed  provided  file path is appended to $HOME directory hence key file path should be relative to user home directory and not absolute.

See result below with entry:
auth        sufficient                                   pam_u2f.so cue authfile=$HOME/.config/Yubico/u2f_keys_pin pinverification=1 {include if "with-pam-u2f"}

the result is:
May 21 12:27:21 host gdm-session-worker[40281]: debug(pam_u2f): util.c:934 (get_devices_from_authfile): Cannot open file: /home/user/$HOME/.config/Yubico/u2f_keys_pin (No such file or directory)
May 21 12:27:21 host gdm-session-worker[40281]: debug(pam_u2f): pam-u2f.c:364 (pam_sm_authenticate): Unable to get devices from file /home/user/$HOME/.config/Yubico/u2f_keys_pin

**Comment by LDVG** [comment]
Hi,

The man pages state that

> Set the location of the file that holds the mappings of user names to keyHandles and user keys. The format is `username:keyHandle1,public_key1:keyHandle2,public_key2:…` the default location of the file is `$XDG_CONFIG_HOME/Yubico/u2f_keys`. If the environment variable is not set, `$HOME/.config/Yubico/u2f_keys` is used. **An individual (per user) file may be configured relative to the users' home dirs, i.e. "`.ssh/u2f_keys`"**.

(emphasis mine). It was added in #127 to clarify the usage of user-individual mappings. This repository's README has a similar phrasing. Do you have a suggestion on how we could clarify it further?

**Comment by perceival** [comment]
Indeed looks like I was too quick reading it. Still if I can propose maybe slightly rephrased? See below.

Set the location of the file that holds the mappings of user names to keyHandles and user keys. An individual (per user) file may be configured relative to the users' home dirs, i.e. ".ssh/u2f_keys". If not specified the default location of the file is $XDG_CONFIG_HOME/Yubico/u2f_keys. If the environment variable is not set, $HOME/.config/Yubico/u2f_keys is used. authfile file format is username:keyHandle1,public_key1:keyHandle2,public_key2:…

**Comment by LDVG** [comment]
We've updated the documentation now, thanks for your report!
