### ISSUE TITLE
Feature request: rejecting not compatible keys if pinverification=1 is set

### ISSUE THREAD

**Issue by perceival** [Yubico/pam-u2f#183]
Is it possible to silently reject older keys unable to support pinverification=1 parameter?
Currently I am using several Yubikeys: NEO, 4 and 5 with two authentication methods:
with default u2f_keys file for authentication not requiring PIN covering all Yubikeys
with separate u2f_pin_keys file for PIN compatible keys for authentication where PIN is requried
In ideal scenario single u2f_keys file should be enough containing all the Yubikeys however if older key is inserted and pinverification=1 is specified authentication is denied.
Currently there appear first PIN prompt and only then authentication is rejected.

**Comment by LDVG** [comment]
You're right, it's currently not possible to achieve this with a single authfile. We'll consider it for the future. Thanks for the request!

**Comment by LDVG** [comment]
Hi @perceival,

I have pushed a tentative implementation of your feature request to the [`opts`](https://github.com/Yubico/pam-u2f/tree/opts) branch of this repository. If you could build it from the source and temporarily point PAM to that build of pam-u2f to see if it satisfies your use-case, that would be greatly appreciated.

Thank you!

**Comment by perceival** [comment]
Hi,I have tried to build it but stumbled upon the following error during make:Making all in .make[1]: Entering directory '/home/percy/pam-u2f'&nbsp; CC&nbsp; &nbsp; &nbsp; &nbsp;pam-u2f.lo&nbsp; CC&nbsp; &nbsp; &nbsp; &nbsp;util.loutil.c: In function ‘do_authentication’:util.c:1340:43: warning: implicit declaration of function ‘fido_dev_supports_uv’; did you mean ‘fido_dev_supports_pin’? [-Wimplicit-function-declaration]&nbsp;1340 |&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;if (opts.uv == FIDO_OPT_FALSE &amp;&amp; !fido_dev_supports_uv(authlist[j]))&nbsp; &nbsp; &nbsp; |&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;^~~~~~~~~~~~~~~~~~~~&nbsp; &nbsp; &nbsp; |&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;fido_dev_supports_pinutil.c:1344:43: warning: implicit declaration of function ‘fido_dev_has_uv’; did you mean ‘fido_dev_has_pin’? [-Wimplicit-function-declaration]&nbsp;1344 |&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;(opts.uv == FIDO_OPT_TRUE &amp;&amp; !fido_dev_has_uv(authlist[j]))) {&nbsp; &nbsp; &nbsp; |&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;^~~~~~~~~~~~~~~&nbsp; &nbsp; &nbsp; |&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;fido_dev_has_pin&nbsp; CC&nbsp; &nbsp; &nbsp; &nbsp;drop_privs.lo&nbsp; CC&nbsp; &nbsp; &nbsp; &nbsp;b64.lo&nbsp; CC&nbsp; &nbsp; &nbsp; &nbsp;explicit_bzero.lo&nbsp; CCLD&nbsp; &nbsp; &nbsp;pam_u2f.la/bin/sh /home/percy/pam-u2f/build-aux/missing a2x --format=manpage -L -a revdate="Version 1.1.2" man/pam_u2f.8.txtmake[1]: Leaving directory '/home/percy/pam-u2f'Making all in pamu2fcfgmake[1]: Entering directory '/home/percy/pam-u2f/pamu2fcfg'gengetopt --no-handle-help --input cmdline.ggo Makefile.ammake&nbsp; all-ammake[2]: Entering directory '/home/percy/pam-u2f/pamu2fcfg'&nbsp; CC&nbsp; &nbsp; &nbsp; &nbsp;pamu2fcfg.o&nbsp; CC&nbsp; &nbsp; &nbsp; &nbsp;cmdline.o&nbsp; CC&nbsp; &nbsp; &nbsp; &nbsp;readpassphrase.o&nbsp; CC&nbsp; &nbsp; &nbsp; &nbsp;strlcpy.o&nbsp; CC&nbsp; &nbsp; &nbsp; &nbsp;../util.o../util.c: In function ‘do_authentication’:../util.c:1340:43: warning: implicit declaration of function ‘fido_dev_supports_uv’; did you mean ‘fido_dev_supports_pin’? [-Wimplicit-function-declaration]&nbsp;1340 |&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;if (opts.uv == FIDO_OPT_FALSE &amp;&amp; !fido_dev_supports_uv(authlist[j]))&nbsp; &nbsp; &nbsp; |&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;^~~~~~~~~~~~~~~~~~~~&nbsp; &nbsp; &nbsp; |&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;fido_dev_supports_pin../util.c:1344:43: warning: implicit declaration of function ‘fido_dev_has_uv’; did you mean ‘fido_dev_has_pin’? [-Wimplicit-function-declaration]&nbsp;1344 |&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;(opts.uv == FIDO_OPT_TRUE &amp;&amp; !fido_dev_has_uv(authlist[j]))) {&nbsp; &nbsp; &nbsp; |&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;^~~~~~~~~~~~~~~&nbsp; &nbsp; &nbsp; |&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;fido_dev_has_pin&nbsp; CC&nbsp; &nbsp; &nbsp; &nbsp;../b64.o&nbsp; CC&nbsp; &nbsp; &nbsp; &nbsp;../explicit_bzero.o&nbsp; CCLD&nbsp; &nbsp; &nbsp;pamu2fcfg/usr/bin/ld: ../util.o: in function `do_authentication':/home/percy/pam-u2f/pamu2fcfg/../util.c:1344: undefined reference to `fido_dev_has_uv'/usr/bin/ld: /home/percy/pam-u2f/pamu2fcfg/../util.c:1340: undefined reference to `fido_dev_supports_uv'collect2: error: ld returned 1 exit statusmake[2]: *** [Makefile:455: pamu2fcfg] Error 1make[2]: Leaving directory '/home/percy/pam-u2f/pamu2fcfg'make[1]: *** [Makefile:360: all] Error 2make[1]: Leaving directory '/home/percy/pam-u2f/pamu2fcfg'make: *** [Makefile:794: all-recursive] Error 1Temat: Re: [Yubico/pam-u2f] Feature request: rejecting not compatible keys if pinverification=1 is set (#183)Data: 2021-08-30 15:38Nadawca: "Ludvig Michaelsson" Adresat: "Yubico/pam-u2f" ; DW: "perceival" ; "Mention" ; 
Hi @perceival,
I have pushed a tentative implementation of your feature request to the opts branch of this repository. If you could build it from the source and temporarily point PAM to that build of pam-u2f to see if it satisfies your use-case, that would be greatly appreciated.
Thank you!

**Comment by LDVG** [comment]
For this patch you'll need libfido2 v1.7.0 or greater. It looks like you're trying to build with an older version of libfido2.

**Comment by perceival** [comment]
Quick first observation: pinverification=0 setting seams to be ignored:
auth        sufficient                                   pam_u2f.so cue pinverification=0
Expected behavior would be for keys regardless whether capable to support PIN or not to not ask for the PIN while Yubikey 5 is requireing PIN for authentication.

**Comment by LDVG** [comment]
Thanks for testing!

> Quick first observation: pinverification=0 setting seams to be ignored:
auth sufficient pam_u2f.so cue pinverification=0
Expected behavior would be for keys regardless whether capable to support PIN or not to not ask for the PIN while Yubikey 5 is requiring PIN for authentication.

Could you clarify, are you being asked for a PIN when setting `pinverification=0`?

If so, does one or more or your credentials in the `authfile` set the `+pin` option?

**Comment by perceival** [comment]
Indeed Yubikey 5 is listed in authfile as `es256,+presence+pin` and from my point of view `pinverification=0` should take precedence before authfile. Instead seems authfile setting is prevailing.

**Comment by LDVG** [comment]
OK. Yes, this is the expected behavior. I can see how this might be unexpected, we may look into clarifying it in the documentation.

Thank you for the feedback!

**Comment by perceival** [comment]
To summarize tested change is going into right direction but for me I will still have to use to authfiles.

**Comment by LDVG** [comment]
> To summarize tested change is going into right direction but for me I will still have to use two authfiles.

If you remove the `+pin` option and rely solely on `pinverification=0` and `pinverification=1`, you should see your requested behavior. Or do you have a requirement for specifying the `+pin` option for some other use case?

**Comment by perceival** [comment]
Brilliant! Somehow I have assumed -N switch  for`pamu2fcfg` is required in order to get prompted for PIN.
Thank you!
PS. might be good to verify `make install` script against selinux compatibility. I had to relabel relevant files for pam-u2f to start working.
