### ISSUE TITLE
pamu2fcfg doesn't support test devices

### ISSUE THREAD

**Issue by semenko** [Yubico/pam-u2f#19]
Hey -- I'm running Ubuntu 15.10 & trying to experiment with pam-u2f. I'm using a test key (provided by Google during the FIDO/U2F Chrome extension development).

This key isn't detected by pamu2fcfg -- but a blue u2f key is detected OK.

I've installed pamu2fcfg:
````
$ apt-cache policy pamu2fcfg
pamu2fcfg:
  Installed: 1.0.1-1
  Candidate: 1.0.1-1
````

It doesn't detect this U2F device:
````
$ pamu2fcfg
(Shows the usual "No U2F device available, please insert one now, you have 15 seconds...")
No device found. Aborting.
````

There's nothing printed to debug, and the device isn't detected regardless of what I do to it (plugged in before/during pamu2fcfg, tapping the device, etc.)

The device shows up in dmesg:
````
[17647.111215] usb 2-1.7: new full-speed USB device number 13 using ehci-pci
[17647.205905] usb 2-1.7: New USB device found, idVendor=1050, idProduct=0211
[17647.205915] usb 2-1.7: New USB device strings: Mfr=1, Product=2, SerialNumber=0
[17647.205920] usb 2-1.7: Product: Yubico WinUSB Gnubby (gnubby1)
[17647.205924] usb 2-1.7: Manufacturer: Yubico
````

And it's set up in a udev rule:
````
ACTION!="add|change", GOTO="fido_end"

ATTRS{idVendor}=="1050", ATTRS{idProduct}=="0010|0110|0111|0114|0116|0211|0401|0403|0405|0407|0410", ENV{ID_SECURITY_TOKEN}="1"

LABEL="fido_end"
````

And it's working great in Chrome both as a Google 2-Step "Security Key" -- and with the demo server (https://demo.yubico.com/u2f).

**Comment by a-dma** [comment]
I am not sure what device that would be.

What I can tell you at this stage is to try with the udev rule in [1] and if that doesn't work, try using `pamu2fcg` with `sudo`.

If you still have no luck, then please send me the serial number of the device (feel free to send it privately) so that I can do some tests with the same device.


[1] - https://github.com/Yubico/libu2f-host/blob/master/70-u2f.rules

**Comment by mirkop** [comment]
The device is a Yubico WinUSB Gnubby and probably does not work as a HID device. Chrome is aparently still supporting Yubico WinUSB devices. I imagine that pam-u2f ONLY works with USB HID devices. Not WinUSB.

**Comment by semenko** [comment]
Ah, thanks @mirkop! Good call.

@a-dma -- the other udev rule didn't work -- presumably because this isn't an HID device.

For completeness, the device doesn't seem to present a serial number.

Via $lsusb:

````
Bus 002 Device 012: ID 1050:0211 Yubico.com 
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               2.00
  bDeviceClass            0 (Defined at Interface level)
  bDeviceSubClass         0 
  bDeviceProtocol         0 
  bMaxPacketSize0        64
  idVendor           0x1050 Yubico.com
  idProduct          0x0211 
  bcdDevice            0.25
  iManufacturer           1 Yubico
  iProduct                2 Yubico WinUSB Gnubby (gnubby1)
  iSerial                 0 
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength           32
    bNumInterfaces          1
    bConfigurationValue     1
    iConfiguration          0 
    bmAttributes         0x80
      (Bus Powered)
    MaxPower               30mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           2
      bInterfaceClass       255 Vendor Specific Class
      bInterfaceSubClass      0 
      bInterfaceProtocol      0 
      iInterface              0 
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x01  EP 1 OUT
        bmAttributes            2
          Transfer Type            Bulk
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0040  1x 64 bytes
        bInterval               0
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x81  EP 1 IN
        bmAttributes            2
          Transfer Type            Bulk
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0040  1x 64 bytes
        bInterval               0
Device Status:     0x0000
  (Bus Powered)
````

**Comment by a-dma** [comment]
Yes @mirkop is correct, that is the issue. A WinUSB device won't work with pam-u2f (more precisely it won't work with libu2f-host) which uses HID.
Support for this is built into Chrome, but not in our tools.

I'm afraid I can't help you there.

I'll close this for now, but please re-open it if you need.
