### ISSUE TITLE
pam-u2f and Linux Mint 20.1 GUI Login

### ISSUE THREAD

**Issue by neilmw1** [Yubico/pam-u2f#192]
I'm having some issues with pam-u2f (cloned from this repo yesterday) and Linux Mint.  

**Background:**
I've built the pam-u2f package succesfully on a brand new Mint 20.1 installation.  I've also used pamu2fcfg to create a pam_u2f mappings file in my $HOME/.config/Yubico directory.  Lastly, I updated common-auth to have this line at the top of the file (above `pam_unix.so`):

`auth    [success=2 default=ignore]      pam_u2f.so pinverification=1`

This configuration works and I am able to sign in without any issues through the Cinnamon/GDM login window, sudo and so on.  I would like to add a cue prompt which tells the user to touch the device when it flashes as it's not obvious at all you need to do this after entering the PIN.  I attempted that with this line instead:

`auth    [success=2 default=ignore]      pam_u2f.so pinverification=1 cue [cue_prompt=Touch your YubiKey]`

**The issue:**

Now, whilst this works and looks great on sudo, for the Cinnamon/GDM Login window there's a problem.  I am asked to enter my PIN, which I do and press enter.  The key flashes _however_ you are not prompted to touch the key until after you've touched it.  This is actually very confusing for a user as they've typed in their PIN, touched the key and then they get a prompt telling them they have to touch the key and click the login button on Mint.

I've tried a few variations such as using Interactive + Prompt but the Username box isn't big enough to put anything meaningful in there.  Any suggestions on how this can be resolved?

Thanks

**Comment by LDVG** [comment]
Hi,

Just to make sure, you are using LightDM (which I believe is the default for for Linux Mint) and not GDM, right? In my testing, GDM3 correctly displays the cue prompt at the correct time whereas LightDM exhibits the issue that you are describing. I'll have a look and see whether we can improve things on our end but from a cursory glance it looks like the fix would need to happen in LightDM (considering that other applications correctly handle the PAM conversation).

**Comment by neilmw1** [comment]
Hi,

Thanks for checking into this for me.  Yes I can confirm it is LightDM and not GDM - I am happy to raise this as an issue with Mint if that's the best option?

Thanks

**Comment by LDVG** [comment]
Hi,

Thanks for confirming. I've had a chance to briefly experiment some more with this. I presume you're using the default greeter, `slick-greeter`. I have tested a couple of other greeters with the following results.

- `slick-greeter`: does not show cue prompt until after the YubiKey has been touched.
- `lightdm-gtk-greeter`: shows the cue prompt correctly, but does not show the `Please Enter the PIN:` prompt.
- `lightdm-webkit2-greeter`: correctly shows all `pam-u2f` prompts
- `ukui-greeter`: correctly shows all `pam-u2f` prompts

Given these results, it would appear that the fix needs to happen in `slick-greeter`.

**Comment by neilmw1** [comment]
Thanks, I've tried ukui-greeter which looks to work okay (except its still asking you to click Login after touching the YubiKey).  I'll go with this for now as it's at least in the correct order - I've reported the issue on the slick-greeter git repo.

**Comment by LDVG** [comment]
Thanks! I'll close this issue for now. Feel free to reopen if we've misunderstood the issue.

Reference: linuxmint/slick-greeter#186
