### ISSUE TITLE
1.0.8 to 1.1.0 breaks keys with differing origin and appID

### ISSUE THREAD

**Issue by programmablereya** [Yubico/pam-u2f#205]
I have a set of shiny new Yubikeys 5 which I recently set up on all my devices, with SSH keys, tap to sudo, etc. All of them were running either Ubuntu Desktop 20.10 (the computers I directly use) or Ubuntu Server 20.04 LTS (my home server), and all of them were running pam-u2f 1.0.8.

On my laptop, I just recently did a dist-upgrade to Ubuntu 20.10 to Ubuntu 21.04. This upgraded my laptop's pam-u2f from 1.0.8 to 1.1.0. 

(The dist-upgrade did also break pam_yubico because the dist-upgrade removed the PPA, which I didn't think about, which was fun :) My sudo configuration was u2f and then yubikey with nothing following that, so I needed to get a LiveUSB together and reinstall the PPA... But that's neither here nor there.)

After this upgrade, the u2f pam module now suggests that _none_ of the keys it has handles for are to be found on my YubiKey, or my portable YubiKeys, or my Google Titan Key...

Some experimentation and exploration showed the reason things are broken, and an easy hack to fix it.

The AppID is not used - _at all_ - anymore. It's accepted, copied from the origin if necessary, deallocated if it was previously allocated... but otherwise completely ignored. Only the origin (RP) is sent to the device for authentication. Evidently, if they were set up in Classic U2F, the authenticator recognizes those things by their AppIDs. And it happened that I set my origin and AppID differently (pam://hostname and pam://sudo@hostname) when I was configuring and registering things a few months back. Hence, my keys are broken.

This is especially confusing because both the origin AND AppID are sent... for registration with pamu2fcfg. (But for whatever reason, a key registered with the different origin and AppID _does_ work with just the origin sent to it. I do not pretend to understand the machinations of this thing. I assume if you have a key handle registered with FIDO2, the origin takes precedence over the AppID, but if you have a key handle registered with FIDO1, the AppID takes precedence over the origin.)

The easy solution, for me, is to just set my origin in the PAM config to my old AppID. (That is, origin=pam://sudo@hostname). All my keys work again that way. I'm also probably going to just reregister them all under FIDO2 in the new format.

Long term, though, it would be nice to have some information about this in the README, which still mentions it as a thing that can be set, a blatant deprecation notice somewhere (maybe in the debug output I was poring over looking for answers), and/or even making it work again using the AppID extension mentioned in [Migrating from U2F](https://developers.yubico.com/WebAuthn/WebAuthn_Developer_Guide/Migrating_from_U2F.html). (It seems libfido2 doesn't support this yet, though.)

**Comment by LDVG** [comment]
Hi,

First of all, we're very sorry for the inconvenience this caused you. I have prepared a patch for this compatibility issue at #206, which should enable users to authenticate again using authfile entries created with `pamu2fcfg` <1.1.0 where the `origin` and `appid` differ. We'd be very grateful if you could have a look and try it out with your keys.

In terms of documentation and behavior of `pamu2fcfg`, I'll have a look and see where we can clarify things regarding the expected behaviour of `origin` and `appid`.

Thank you for reporting this.

Thanks!

**Comment by programmablereya** [comment]
Thanks for getting back to me on this so quickly - I'll check it out and verify that it works right away! :)

**Comment by programmablereya** [comment]
Confirmed success! :)

I removed the newly registered device that I created with `pamu2fcfg` 1.1.0, and with just the old device list and this pam config:
```
auth       optional                 altered/pam_u2f.so    origin=pam://<full hostname> appid=pam://sudo@<full hostname> authfile=<U2F devices path> cue [cue_prompt=Please touch the device. (patched pam_u2f.so)] interactive [prompt=Please insert the device. (patched pam_u2f.so)] userpresence=1
 auth       sufficient                 pam_u2f.so    origin=pam://<full hostname> appid=pam://sudo@<full hostname> authfile=<U2F devices path> cue [cue_prompt=Please touch the device (stock pam_u2f.so)] interactive [prompt=Please insert the device. (stock pam_u2f.so)] userpresence=1
 auth       [success=done default=die] pam_yubico.so authfile=<Yubikey devices path> id=<Yubico API ID> key=<Yubico API key> mode=client
```

I got this result:
```
[ OK] reya@mordhona:~ 
$ sudo -k
[ OK] reya@mordhona:~ 
$ sudo -s
Please insert the device. (patched pam_u2f.so)
Please touch the device. (patched pam_u2f.so)
Please insert the device. (stock pam_u2f.so)
YubiKey for `reya': 
root@mordhona:/home/reya# 
```

Which looks like a success to me - the stock one fails in finding the device with the same input where the patched one succeeds! :)

Thanks for your hard work on this!

**Comment by LDVG** [comment]
Thank you for the swift feedback, I'm glad that to hear that it helped!

**Comment by programmablereya** [comment]
Love the documentation updates - thanks so much for such a complete fix! :)

**Comment by LDVG** [comment]
Glad to hear! Thanks again for the report!
