### ISSUE TITLE
Didn't work on macOS 11.4: drop_privs.c:118 (pam_modutil_regain_priv)

### ISSUE THREAD

**Issue by Anebrithien** [Yubico/pam-u2f#207]
1. MacBook Pro (Retina, 13-inch, Early 2015).
2. Yubikey 5 NFC
3. macOS 11.4
4. Install `pam-u2f` by `brew install pam-u2f`

Here is my `/etc/pam.d/sudo` file:

```
# add u2f support
auth       sufficient     /usr/local/opt/pam-u2f/lib/pam/pam_u2f.so cue
# sudo: auth account password session
auth       sufficient     pam_smartcard.so
auth       required       pam_opendirectory.so
account    required       pam_permit.so
password   required       pam_deny.so
session    required       pam_permit.so
```

It works like what documents said, even after upgrade macOS to big Sur.

But I got a debug message today:

```
debug(pam_u2f): drop_privs.c:118 (pam_modutil_regain_priv): setgroups: Invalid argument
```

1. With Yubikey 5 NFC connected, I got the debug message and could not touch Yubikey to pass sudo auth.
2. Without Yubikey 5 NFC, I got the same debug message after `sudo` command.

**Comment by axeII** [comment]
I have same problem on macbook air M1 on macOS 11.4. Yubikey usb-c 😞 .

**Comment by LDVG** [comment]
Thank you for reporting this issue! We've managed to reproduce this issue and are looking into a possible fix. One way to workaround this in the meantime is to switch to a system-level authorization file owned by `root`, for further information please see the documentation about [Central Authorization Mapping](https://github.com/Yubico/pam-u2f#central-authorization-mapping).

**Comment by Anebrithien** [comment]
> Thank you for reporting this! We've managed to reproduce the issue and are looking into a possible fix. One way to workaround this in the meantime is to switch to a system-level authorization file owned by `root`, for further information please see the documentation about [Central Authorization Mapping](https://github.com/Yubico/pam-u2f#central-authorization-mapping).

Thank you for the advice. The workaround works!

**Comment by Anebrithien** [comment]
I have tested `pam-u2f` on my macOS(11.5.2), it works now.

After some search, I compiled pam_u2f.so on macOS, here is `/etc/pam.d/sudo` file:

```
# add u2f support
auth       sufficient     /path/to/git/pam-u2f/.libs/pam_u2f.so cue
# sudo: auth account password session
auth       sufficient     pam_smartcard.so
auth       required       pam_opendirectory.so
account    required       pam_permit.so
password   required       pam_deny.so
session    required       pam_permit.so
```

Thanks your hard work. @LDVG
