### ISSUE TITLE
Update version on aptitude

### ISSUE THREAD

**Issue by dlo** [Yubico/pam-u2f#21]
The version that's currently installed via `apt-get install pam-u2f` has a few differences from the current one up on GitHub, notably:

1. The default key directory is .yubico/u2f_keys versus .config/Yubico/u2f_keys in the newer version
2. It doesn't appear to respect the "manual" or "interactive" attributes in the pam module.

**Comment by a-dma** [comment]
which source are you using? On which distro/version? If you're installing from our PPA or Debian testing the versions should be in sync.

Please paste the output of `apt-cache policy pam-u2f`.

**Comment by a-dma** [comment]
Closed for lack of activity.
