### ISSUE TITLE
Missing include for u2f-host and u2f-server

### ISSUE THREAD

**Issue by nbars** [Yubico/pam-u2f#22]
Hello,
I got the following error while trying to compile the pam-u2f library:
```
make[1]: Entering directory '.../pam_u2f/pam_u2f/src/pam_u2f-1.0.1'
  CC       util.lo
In file included from util.c:8:0:
/usr/include/u2f-host/u2f-host.h:24:30: fatal error: u2f-host-version.h: No such file or directory
```

 I am not sure if my fix is correct because I have never worked with the build system that is used by your project. Inside the Makefile.am file I have changed the line
```AM_CFLAGS = $(WARN_CFLAGS) ```
to
```AM_CFLAGS = $(WARN_CFLAGS)  $(LIBU2FHOST_CFLAGS) $(LIBU2FSERVER_CFLAGS)```

**Comment by a-dma** [comment]
Hey,
that seems like a problem with u2f-host.
Which version of libu2f-host are you using? Are you building everything from source or just pam-u2f? Judging by your paths it looks like you've installed libu2f-host from the PPA? Also I'm assuming Ubuntu here, if not please tell me.

Try running `pkg-config --cflags u2f-host` and past the output. Also make sure you have the latest version of libu2f-host (currently 1.0.0).

**Comment by nbars** [comment]
Sorry that I did not provide enough information's.
I am building on arch linux and have ```u2f-host 1.0.0``` installed.

I installed the u2f-host and u2f-server libs from the packages provided by the arch repositories.

Output from ```pkg-config --cflags u2f-host```
```
pkg-config --cflags u2f-host
-I/usr/include/u2f-host 
```

**Comment by a-dma** [comment]
No problems.

Are you by chance using automake 1.15? If so that could be the culprit here.

**Comment by nbars** [comment]
Yes, I am using automake 1.15. What is the problem with this version? And what would be the right way to fix it?

**Comment by Ikke** [comment]
Same problem here. Also Archlinux with automake 1.15.

**Comment by a-dma** [comment]
We're figuring this out. It seems related to automake 1.15, but it builds fine on Ubuntu 10.15 which has that version.
Anyway, for this specific project is fine to just add the variables to CFLAGS rather than CPPFLAGS.

**Comment by a-dma** [comment]
Actually, scrap that.
There is a new release of the project (version 1.0.2) could you please have a look at that?

**Comment by nbars** [comment]
It now compiles just fine!
Thank you.

**Comment by a-dma** [comment]
Good, thanks for helping out!
