### ISSUE TITLE
Yubikey serial-api-visible Error

### ISSUE THREAD

**Issue by Nalum** [Yubico/pam-u2f#221]
I've got 2 Yubikey setup and am running Manjaro Linux. I have installed `yubico-pam-2.27-1` and setup the following line in `/etc/pam.d/sudo` (where `[hostname]` is my hostname):

```
#%PAM-1.0
auth            sufficient      pam_u2f.so cue origin=pam://[hostname] appid=pam://[hostname]
auth            include         system-auth
account         include         system-auth
session         include         system-auth
```

When I run `sudo` commands I get the following error with 1 of the keys where the other key is fine:

```
debug: util.c:582 (get_user_challenge_file): Failed to read serial number (serial-api-visible disabled?).
```

Using `ykinfo -s` I am able to get the serial number for both keys, not sure if this shows that `serial-api-visible` is enabled or not.

Any help is appreciated, I'm honestly not sure if the issue is with pam-u2f (seems unlikely) or how I've setup the yubikey (seems more likely), I didn't do anything different with either key and running `ykpamcfg -2` works as expected.

**Comment by LDVG** [comment]
Hi,

First of all, are you trying to configure/use [`yubico-pam`](https://github.com/yubico/yubico-pam) or [`pam-u2f`](https://github.com/yubico/pam-u2f)? The PAM service configuration you quoted suggests `pam-u2f` whereas the debug message and `ykpamcfg` utility both belong to `yubico-pam`.

**Comment by Nalum** [comment]
I'm trying to configure `pam-u2f`, I thought they were related. I have `pam-u2f-1.1.1-1` installed on my system.

I have both keys setup in `~/.config/Yubico/u2f_keys`, using this command:
```
$ HOSTNAME=$(hostname); pamu2fcfg -o pam://$HOSTNAME -i pam://$HOSTNAME  >> ~/.config/Yubico/u2f_keys
```

**Comment by LDVG** [comment]
OK!

Just to clarify, `pam-u2f` and `yubico-pam` and their respective tools are completely standalone.

Now, onto your problem, could you check the format of your `authfile` (`~/.config/Yubico/u2f_keys`)?

A correctly formatted `authfile` for a user with two authenticators configured should have a single line in the following format

```
<username>:<key handle 1>,<public key 1>,<key type 1>,<options 1>:<key handle 2>,<public key 2>,<key type 2>,<options 2>
```

Note how the username is only specified once and how multiple credentials are separated by a colon.

For future reference, you may find `pamu2fcfg`'s `--nouser` flag useful for configuring multiple authenticators.

```shell
$ pamu2fcfg -o pam://$HOSTNAME -i pam://$HOSTNAME >> ~/.config/Yubico/u2f_keys
$ pamu2fcfg -o pam://$HOSTNAME -i pam://$HOSTNAME --nouser >> ~/.config/Yubico/u2f_keys
```

**Comment by Nalum** [comment]
I have two separate lines in the file as follows:
```
nalum:<key1>,<key2>,es256,+presence
nalum:<key1>,<key2>,es256,+presence
```

Should I combine that into a single line as you have noted:
```
nalum:<key1>,<key2>,es256,+presence:<key1>,<key2>,es256,+presence
```

**Comment by LDVG** [comment]
Yes, combine the two lines, otherwise `pam-u2f` will only take the last line for the specified user into account. :slightly_smiling_face:

**Comment by Nalum** [comment]
Thank you very much for your help, that's sorted the issue for me :+1:

**Comment by LDVG** [comment]
> Thank you very much for your help, that's sorted the issue for me

Happy to help!
