### ISSUE TITLE
util.c : Add option to silently failover to another auth method

### ISSUE THREAD

**Issue by tomswartz07** [Yubico/pam-u2f#23]
Hi there!

Thank you very much for this project, I am very glad to be able to use it in my work and projects.

I do have one feature request:

If attempting to auth without the key inserted, a message appears:
`[util.c:do_authentication(233)] Unable to discover device(s), cannot find U2F device`

It seems to be related to the fact that [util.c is (seemingly) lacking a check for missing devices](https://github.com/Yubico/pam-u2f/blob/master/util.c#L235-L242).

Would it be possible to expand this so that the module silently passes to the next authentication module?
I'd be happy to submit a pull request if you would provide some insight into a preferred fix.

Here's my relevant configuration:

**OS:** ArchLinux, 4.2.1 Kernel

**/etc/pam.d/sudo**
```                                                             
#%PAM-1.0
auth		sufficient	pam_u2f.so cue
auth		include		system-auth
account		include		system-auth
session		include		system-auth
```

**Auth while missing the key:**
```
$ sudo su
[util.c:do_authentication(233)] Unable to discover device(s), cannot find U2F device
[sudo] password for tom:
```

Again, thanks so much for the work!

**Comment by a-dma** [comment]
Hi,
I'm glad that you find this project useful.

So, is it just a matter of not printing the message or are you having troubles with PAM not using the following module?

If it's the latter try something like this
```
auth   [success=1 default=ignore]  pam_u2f.so
auth   requisite                   pam_unix.so
auth   required                    pam_permit.so
```

If instead it's just the print bothering you I can push something tomorrow to fix that. I'm still trying to decide whether or not is bad not to give the user any message at all if debug is turned off.

**Comment by tomswartz07** [comment]
Hi @a-dma:

I've tried with the `[success=1 default=ignore]` edits, as you've suggested and it still outputs the text I highlight in my original post.

I think that the text that's output  would be most helpful in 'debug mode', but not during normal operation.

If you plan to use the U2F device, you'll either have it plugged in before auth'ing, or use the 'interactive' mode to prompt you to plug and touch the device.

**Comment by a-dma** [comment]
I pushed a new version, let me know if that works for you.

**Comment by Manouchehri** [comment]
I can confirm that b5729e8cc9ce6794b3f53661fe10d5b78b992404 fixes it. Thanks @a-dma!

Before:
```
~ > sudo whoami
[util.c:do_authentication(236)] Unable to discover device(s), cannot find U2F device
YubiKey for `david': 
root
```

After:
```
~ > sudo whoami
YubiKey for `david': 
root
```

**Comment by tomswartz07** [comment]
@a-dma Sorry for the delay. Yes, I can also confirm that the updated version works as well!

Thanks!

**Comment by a-dma** [comment]
No worries. Closing.
