### ISSUE TITLE
Multiple U2F key entries in authfile require a touch for each entry until success

### ISSUE THREAD

**Issue by timfallmk** [Yubico/pam-u2f#247]
I'm trying to setup a central auth file that contains multiple U2F keys per user (in this case, three different types of YubiKey). Following the readme, I've generated three keypairs for my user and appended the lines to my user entry in the style
```shell
<username>:<KeyHandle1>,<UserKey1>,<CoseType1>,<Options1>:<KeyHandle2>,<UserKey2>,<CoseType2>,<Options2>:<KeyHandle3>,<UserKey3>,<CoseType3>,<Options3>
```
And enabled debugging during the auth flow. When I attempt to authenticate, each entry is checked sequentially but _I have to tap the inserted key for each one_ until it reaches the correct entry. Is this the intended behavior? As a side note the cue prompt will only appear once, and the only indication that a user has that further touches are needed is the blinking light on the key.

I'm wondering if the fact that every `KeyHandle` generated is `*` has anything to do with this. I used the `pamu2fcfg -n --resident` option when creating them.

**Comment by LDVG** [comment]
Yes, this is the expected behavior. When using resident (discoverable) credentials, no key handle is stored and `pam-u2f` attempts authentication with all currently connected authenticators.

**Comment by LDVG** [comment]
Yes, when using non-discoverable credentials, the key handle is stored and `pam-u2f` performs a "pre-flight" check to test if the credential is present in any of the connected authenticators, minimizing the number of required touches.
