### ISSUE TITLE
1.0.2 from PPA dumps core on Ubuntu 15.10 64-bit

### ISSUE THREAD

**Issue by chill633** [Yubico/pam-u2f#26]
A fresh install of Ubuntu 15.10 64-bit, added the PPA and installed pamu2fcfg 1.0.2. Using Yubikey NEO w/firmware 3.4.3. Executing pamu2fcfg causes the LED on the Yubikey to blink, then causes a segfault. 

I don't have write permission, so can't attach dump.

Here is the debug output:

chill@chill-laptop:~$ pamu2fcfg -d
USB send: 00ffffffff8600080807060504030201000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
USB write returned 65
now trying with timeout 2
USB read rc read 64
USB recv: ffffffff86001108070605040302010100b3a8020101000100000000000000000000000000000000000000000000000000000000000000000000000000000000
device /dev/hidraw5 discovered as 'Yubikey NEO OTP+U2F+CCID'
  version (Interface, Major, Minor, Build): 2, 1, 1, 0  capFlags: 1
JSON: { "challenge": "dctvVk9NalieD7JRSgS8A4eoA1yx79reAgYK9y0vtYA", "version": "U2F_V2", "appId": "pam:\/\/chill-laptop" }
JSON challenge URL-B64: dctvVk9NalieD7JRSgS8A4eoA1yx79reAgYK9y0vtYA
client data: { "challenge": "dctvVk9NalieD7JRSgS8A4eoA1yx79reAgYK9y0vtYA", "origin": "pam:\/\/chill-laptop", "typ": "navigator.id.finishEnrollment" }
JSON: { "challenge": "dctvVk9NalieD7JRSgS8A4eoA1yx79reAgYK9y0vtYA", "version": "U2F_V2", "appId": "pam:\/\/chill-laptop" }
JSON app_id pam://chill-laptop
USB send: 000100b3a883004700010300000040d4a79dc250ed813df4c3bb063418416b575b02ca8524dc8950adf47198d56e6af116c09420dee0d966d62b2075542db20c
USB write returned 65
USB send: 000100b3a8001b12286e563a537c54c4be7017fe0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
USB write returned 65
now trying with timeout 2
now trying with timeout 4
now trying with timeout 8
now trying with timeout 16
USB read rc read 64
USB recv: 0100b3a8830002698500000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
USB data (len 2): 6985
USB send: 000100b3a883004700010300000040d4a79dc250ed813df4c3bb063418416b575b02ca8524dc8950adf47198d56e6af116c09420dee0d966d62b2075542db20c
USB write returned 65
USB send: 000100b3a8001b12286e563a537c54c4be7017fe0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
USB write returned 65
now trying with timeout 2
now trying with timeout 4
now trying with timeout 8
USB read rc read 64
USB recv: 0100b3a8830002698500000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
USB data (len 2): 6985
USB send: 000100b3a883004700010300000040d4a79dc250ed813df4c3bb063418416b575b02ca8524dc8950adf47198d56e6af116c09420dee0d966d62b2075542db20c
USB write returned 65
USB send: 000100b3a8001b12286e563a537c54c4be7017fe0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
USB write returned 65
now trying with timeout 2
now trying with timeout 4
now trying with timeout 8
USB read rc read 64
USB recv: 0100b3a8830002698500000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
USB data (len 2): 6985
USB send: 000100b3a883004700010300000040d4a79dc250ed813df4c3bb063418416b575b02ca8524dc8950adf47198d56e6af116c09420dee0d966d62b2075542db20c
USB write returned 65
USB send: 000100b3a8001b12286e563a537c54c4be7017fe0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
USB write returned 65
now trying with timeout 2
now trying with timeout 4
now trying with timeout 8
USB read rc read 64
USB recv: 0100b3a8830002698500000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
USB data (len 2): 6985
USB send: 000100b3a883004700010300000040d4a79dc250ed813df4c3bb063418416b575b02ca8524dc8950adf47198d56e6af116c09420dee0d966d62b2075542db20c
USB write returned 65
USB send: 000100b3a8001b12286e563a537c54c4be7017fe0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
USB write returned 65
now trying with timeout 2
now trying with timeout 4
now trying with timeout 8
USB read rc read 64
USB recv: 0100b3a8830002698500000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
USB data (len 2): 6985
USB send: 000100b3a883004700010300000040d4a79dc250ed813df4c3bb063418416b575b02ca8524dc8950adf47198d56e6af116c09420dee0d966d62b2075542db20c
USB write returned 65
USB send: 000100b3a8001b12286e563a537c54c4be7017fe0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
USB write returned 65
now trying with timeout 2
now trying with timeout 4
now trying with timeout 8
USB read rc read 64
USB recv: 0100b3a8830002698500000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
USB data (len 2): 6985
USB send: 000100b3a883004700010300000040d4a79dc250ed813df4c3bb063418416b575b02ca8524dc8950adf47198d56e6af116c09420dee0d966d62b2075542db20c
USB write returned 65
USB send: 000100b3a8001b12286e563a537c54c4be7017fe0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
USB write returned 65
now trying with timeout 2
now trying with timeout 4
now trying with timeout 8
USB read rc read 64
USB recv: 0100b3a8830002698500000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
USB data (len 2): 6985
USB send: 000100b3a883004700010300000040d4a79dc250ed813df4c3bb063418416b575b02ca8524dc8950adf47198d56e6af116c09420dee0d966d62b2075542db20c
USB write returned 65
USB send: 000100b3a8001b12286e563a537c54c4be7017fe0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
USB write returned 65
now trying with timeout 2
now trying with timeout 4
now trying with timeout 8
USB read rc read 64
USB recv: 0100b3a8830002698500000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
USB data (len 2): 6985
USB send: 000100b3a883004700010300000040d4a79dc250ed813df4c3bb063418416b575b02ca8524dc8950adf47198d56e6af116c09420dee0d966d62b2075542db20c
USB write returned 65
USB send: 000100b3a8001b12286e563a537c54c4be7017fe0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
USB write returned 65
now trying with timeout 2
now trying with timeout 4
now trying with timeout 8
USB read rc read 64
USB recv: 0100b3a8830002698500000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
USB data (len 2): 6985
USB send: 000100b3a883004700010300000040d4a79dc250ed813df4c3bb063418416b575b02ca8524dc8950adf47198d56e6af116c09420dee0d966d62b2075542db20c
USB write returned 65
USB send: 000100b3a8001b12286e563a537c54c4be7017fe0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
USB write returned 65
now trying with timeout 2
now trying with timeout 4
now trying with timeout 8
USB read rc read 64
USB recv: 0100b3a8830002698500000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
USB data (len 2): 6985
USB send: 000100b3a883004700010300000040d4a79dc250ed813df4c3bb063418416b575b02ca8524dc8950adf47198d56e6af116c09420dee0d966d62b2075542db20c
USB write returned 65
USB send: 000100b3a8001b12286e563a537c54c4be7017fe0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
USB write returned 65
now trying with timeout 2
now trying with timeout 4
now trying with timeout 8
USB read rc read 64
USB recv: 0100b3a8830002698500000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
USB data (len 2): 6985
USB send: 000100b3a883004700010300000040d4a79dc250ed813df4c3bb063418416b575b02ca8524dc8950adf47198d56e6af116c09420dee0d966d62b2075542db20c
USB write returned 65
USB send: 000100b3a8001b12286e563a537c54c4be7017fe0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
USB write returned 65
now trying with timeout 2
now trying with timeout 4
now trying with timeout 8
USB read rc read 64
USB recv: 0100b3a8830002698500000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
USB data (len 2): 6985
USB send: 000100b3a883004700010300000040d4a79dc250ed813df4c3bb063418416b575b02ca8524dc8950adf47198d56e6af116c09420dee0d966d62b2075542db20c
USB write returned 65
USB send: 000100b3a8001b12286e563a537c54c4be7017fe0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
USB write returned 65
now trying with timeout 2
now trying with timeout 4
now trying with timeout 8
USB read rc read 64
USB recv: 0100b3a8830002698500000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
USB data (len 2): 6985
USB send: 000100b3a883004700010300000040d4a79dc250ed813df4c3bb063418416b575b02ca8524dc8950adf47198d56e6af116c09420dee0d966d62b2075542db20c
USB write returned 65
USB send: 000100b3a8001b12286e563a537c54c4be7017fe0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
USB write returned 65
now trying with timeout 2
now trying with timeout 4
now trying with timeout 8
USB read rc read 64
USB recv: 0100b3a8830002698500000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
USB data (len 2): 6985
USB send: 000100b3a883004700010300000040d4a79dc250ed813df4c3bb063418416b575b02ca8524dc8950adf47198d56e6af116c09420dee0d966d62b2075542db20c
USB write returned 65
USB send: 000100b3a8001b12286e563a537c54c4be7017fe0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
USB write returned 65
now trying with timeout 2
now trying with timeout 4
now trying with timeout 8
USB read rc read 64
USB recv: 0100b3a8830002698500000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
USB data (len 2): 6985
USB send: 000100b3a883004700010300000040d4a79dc250ed813df4c3bb063418416b575b02ca8524dc8950adf47198d56e6af116c09420dee0d966d62b2075542db20c
USB write returned 65
USB send: 000100b3a8001b12286e563a537c54c4be7017fe0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
USB write returned 65
now trying with timeout 2
now trying with timeout 4
now trying with timeout 8
USB read rc read 64
USB recv: 0100b3a8830002698500000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
USB data (len 2): 6985
Segmentation fault (core dumped)

**Comment by a-dma** [comment]
I've pushed new code with a fix, could you please build HEAD and confirm that solves the issue for you please?

If so I'll make a release early next week.

Thanks.

**Comment by chill633** [comment]
Solved! Thank you!

**Comment by a-dma** [comment]
1.0.3 is out.
