### ISSUE TITLE
Key not found in authenticator 0

### ISSUE THREAD

**Issue by robko23** [Yubico/pam-u2f#267]
I have Yubikey 5 NFC and I have been using this pam module for about two months. Everthing worked fine until now.
I have following config line in pam module
```
auth       sufficient   pam_u2f.so debug authfile=/etc/u2f_mappings cue pinverification=1
```
And now it prints this: https://pastebin.com/41BTPabK
What I don't understand is these three lines
```
debug(pam_u2f): util.c:984 (get_authenticators): Key not found in authenticator 0
debug(pam_u2f): util.c:995 (get_authenticators): Key not found
debug(pam_u2f): util.c:1450 (do_authentication): Device for this keyhandle is not present
```
Interestingly, when I enter this command
`pamu2fcfg -urobko -opam://fedora -ipam://fedora`
It functions normally and produces following output
```
Enter PIN for /dev/hidraw1: 
robko:LPpp4mnoBzll0H3CcApVyb7PxynrqeyvKZDfzmJmAJVpS391cft5CgSOwI5D4cWbjvEse6/7ebCq38GWgYhWzg==,6NlO49Qugkzx7WQmCi37YhSMEyc7mxaVl3JPPkAvcQFZNyUDsLXtmy1CyLhabgEjdSdWLPF/D/7PbFYviEzgxA==,es256,+presence
```
So I think that the key is on the card and it functions somewhat correctly.
I have been looking for any update that could have caused this and none of the dependencies have upated.

System info (`uname -a`):
```
Linux fedora 5.17.6-300.fc36.x86_64 #1 SMP PREEMPT Mon May 9 15:47:11 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```
Any ideas what could have caused this?

**Comment by LDVG** [comment]
> What I don't understand is these three lines
> ```
> debug(pam_u2f): util.c:984 (get_authenticators): Key not found in authenticator 0
> debug(pam_u2f): util.c:995 (get_authenticators): Key not found
> debug(pam_u2f): util.c:1450 (do_authentication): Device for this keyhandle is not present
> ```

These messages are logged when pam-u2f looks for the credential(s) referenced by your `authfile` in the connected authenticator(s) (in your case, the YubiKey) and all of them indicate that they do not recognise it.

If you have previously used this same YubiKey successfully with pam-u2f, have you recently either
1. Reset the FIDO2 application on the YubiKey?
2. Changed the hostname of the machine you're trying to authenticate on?

> Interestingly, when I enter this command
> ```
> pamu2fcfg -urobko -opam://fedora -ipam://fedora
> ```
> It functions normally [...]

This registers an additional credential for use with pam-u2f in your YubiKey and does not query for any present credentials.

> I have been looking for any update that could have caused this and none of the dependencies have upated.

What version of pam-u2f and libfido2 are you currently using?

**Comment by robko23** [comment]
Yes, I changed the hostname on the machine. So I tried to re-register the key only with 
```
pamu2fcfg | sudo tee /etc/u2f_mappings
```

and it is working now. Thanks!
