### ISSUE TITLE
automated test case failure

### ISSUE THREAD

**Issue by anon8675309** [Yubico/pam-u2f#270]
The one of automated tests appears to be failing due to a crash.  Punchline is pasted below, but the full logs can be found [here](https://salsa.debian.org/adam_hax/pam-u2f/-/jobs/2907815#L968).  This is preventing the reproducible builds pipeline from completing successfully.

```
PASS: basic
get_devices: get_devices.c:42: main: Assertion `username != NULL' failed.
/bin/bash: line 6:  4563 Aborted                 (core dumped) ${dir}$tst
FAIL: get_devices
=========================================================
1 of 2 tests failed
Please report to https://github.com/Yubico/pam-u2f/issues
=========================================================
```

**Comment by LDVG** [comment]
Hi,

Thanks for reporting. The test is failing because the environment does not have `$USER` set, which the test case itself relies on. While we implement something more robust, a quick fix should be to set `USER=$(whoami)`.
