### ISSUE TITLE
Pamu2f doesn't fallback to PIN when blocking the Yubikey by touching it wrong more than 3 times

### ISSUE THREAD

**Issue by SmoZy92** [Yubico/pam-u2f#276]
Hello,

I am facing an issue on implementing Biometric Yubikey for login on Ubuntu.

I have generated my u2f key file with pamu2fcfg 

then to test, I first went for sudo before login to avoid being locking in.

Here is my sudo file under pam.d

```
# Set up user limits from /etc/security/limits.conf.
session    required   pam_limits.so

@include common-auth
auth       required   pam_u2f.so authfile=/etc/Yubico/u2f_keys cue nouserok
@include common-account
@include common-session-noninteractive
```

The issue is when I touch wrong 3 times in a row the Yubikey, the Yubikey then get locked and I have no fallback on the PIN, it keep asking for the yubikey to be touched and failling again and again because it is locked.

Is there any way to ask for PIN when the Yubikey is locked (3 wrong touch in a row) ?

Thanks

**Comment by LDVG** [comment]
Hi,

Could something like

```shell
# Attempt user verification via fingerprint.
auth    [success=1 default=ignore]  pam_u2f.so authfile=/etc/Yubico/u2f_keys cue nouserok userverification=1
# Fallback to PIN authentication.
auth    [success=ok default=bad]    pam_u2f.so authfile=/etc/Yubico/u2f_keys cue nouserok pinverification=1
```

work for your use-case? It will not wait for fingerprint matching to be blocked entirely, but immediately fall back to a PIN.

Thank you!

Ludvig

**Comment by SmoZy92** [comment]
> Hi,
> 
> Could something like
> 
> ```shell
> # Attempt user verification via fingerprint.
> auth    [success=1 default=ignore]  pam_u2f.so authfile=/etc/Yubico/u2f_keys cue nouserok userverification=1
> # Fallback to PIN authentication.
> auth    [success=ok default=bad]    pam_u2f.so authfile=/etc/Yubico/u2f_keys cue nouserok pinverification=1
> ```
> 
> work for your use-case? It will not wait for fingerprint matching to be blocked entirely, but immediately fall back to a PIN.
> 
> Thank you!
> 
> Ludvig

Hey Ludvig, hope you are doing well.

Thank you for the reply, it helped me to find a workaround with pamd. The workaround will ask for the PIN if 3 touch attempts fails. For anyone looking for the solution, find the workaround below

`auth    [success=4 default=ignore]      pam_u2f.so authfile=/etc/Yubico/u2f_keys nouserok userverification=1 cue [cue_prompt=Touch the Yubikey]
auth    [success=3 default=ignore]      pam_u2f.so authfile=/etc/Yubico/u2f_keys nouserok userverification=1 cue [cue_prompt=Wrong touch, try again 2 attempts remaining before locking the Yubikey]
auth    [success=2 default=ignore]      pam_u2f.so authfile=/etc/Yubico/u2f_keys nouserok userverification=1 cue [cue_prompt=Wrong touch, try again last attempt remaining before locking the Yubikey]
auth    [success=1 default=ignore]      pam_u2f.so authfile=/etc/Yubico/u2f_keys nouserok pinverification=1 userverification=1 cue
auth    required   pam_u2f.so authfile=/etc/Yubico/u2f_keys nouserok pinverification=1 userverification=1 cue`
