### ISSUE TITLE
Question: is it possible to Skip u2f login without unplugging the FIDO device?

### ISSUE THREAD

**Issue by My1** [Yubico/pam-u2f#279]
(I know this isnt the best place but the discussions feature isnt on here and the Yubico forum is dead)

I have a pretty successful Setup on my Kubuntu 22.04 by now which allows me to both unlock the screen and sudo with my FIDO device, which is great, and I am running `sufficient` in order to fall back to password if needed, however one thing I cannot figure out yet, is how to skip the fido module when the FIDO Device is still plugged in.

This is in order to enable me to still use my computer from afar, where it would kinda be annoying to force presence or ask someone to unplug it

pam -> common-auth
```
# here are the per-package modules (the "Primary" block)
auth    sufficient pam_u2f.so authfile=/etc/pamfido/u2f_keys cue prompt nouserok
auth    [success=1 default=ignore]      pam_unix.so nullok
# here's the fallback if no module succeeds
auth    requisite                       pam_deny.so
# prime the stack with a positive return value if there isn't one already;
# this avoids us returning an error just because nothing sets a success code
# since the modules above will each just jump around
auth    required                        pam_permit.so
# and here are more per-package modules (the "Additional" block)
auth    optional                        pam_cap.so
# end of pam-auth-update config
```

**Comment by LDVG** [comment]
There's no built-in way of skipping the authentication other than `nouserok`. You could skip it through the PAM stack itself by using another module to check some condition that is only true for a particular user when connected remotely; `pam_exec(8)` or similar, may be of interest.

**Comment by My1** [comment]
nouserok does not just skip the pam_fido but it skips EVERYTHING for a user that doesnt have fido setup (as in it doesnt even ask for the password for my backup user, so I ended up removing the word.

**Comment by LDVG** [comment]
Sorry, I should have elaborated. Yes, `nouserok` forces the module to return successfully if the user does not exist in the authorization mapping file (rather than an error), which "skips" the module for that user. This behavior enables PAM stacks such as

```
auth required pam_u2f.so nouserok 
auth required pam_unix.so
```

or similar. In either case, `nouserok` would not help with the question in the OP.

**Comment by My1** [comment]
I see, thanks for the info. while not quite what I would have loved to see, it's likely not easy to tell the module "this isnt a pin, use it as a password, and you dont really get a choice prompt either". thanks tho.

**Comment by LDVG** [comment]
Indeed. I'll go ahead and close this as "not planned". For the original ask, I'll again point towards `pam_succeed_if(8)`, `pam_exec(8)` and friends to make a particular PAM entry conditional.
