### ISSUE TITLE
libpam-u2f and ubuntu 22.04 error: yubico ubuntu login segmentation fault (core dumped)

### ISSUE THREAD

**Issue by canutodev** [Yubico/pam-u2f#290]
Hello,
i followed these instructions to the letter (https://support.yubico.com/hc/en-us/articles/360016649099-Ubuntu-Linux-Login-Guide-U2F) but as soon as i run "sudo echo test" to test the setup I get "segmentation fault (core dumped)" right away. The operating system is Ubuntu 22.04, the ybikey is 5nfc. I use the key with gpg without problems but with libpam-u2f I have this problem. Can you help me?

Best regards.

**Comment by LDVG** [comment]
Hi,

I was unable to reproduce this problem. Could you please share with us:

- the installed version of `libpam-u2f`, `libfido2`, and `libpam-runtime`;
- the contents of `/etc/pam.d/sudo` (and any other file you may have modified in the `/etc/pam.d` directory);
- the output of an authentication attempt after appending the `debug`  argument to the configuration (i.e. `auth required pam_u2f.so debug`);
- any errors printed by `journalctl -e -t sudo` during the authentication attempt;
- the output of `ldd /usr/lib/x86_64-linux-gnu/security/pam_u2f.so`.

Thank you!
