### ISSUE TITLE
More descriptive error messages

### ISSUE THREAD

**Issue by LecrisUT** [Yubico/pam-u2f#291]
### Is your feature request related to a problem?

On a Fedora KDE install, using the following pam configuration
```
auth        requisite                                    pam_u2f.so cue
```

We get non-descriptive error messages like `invalid login` when the yubikey is not present, instead of a message like: `Required yubikey not present`.

### Describe the solution that you'd like
Print out more descriptive errors:
- `Required yubikey not present`
- `Invalid yubikey found`
- etc.

**Comment by LDVG** [comment]
Hi,

Thank you for your request! This has some similarity to the proposed solution to #209. The suggested implementation can be found under the _experimental_ `cue` branch . If you want to give that a go, we'd be happy for any feedback. 

Note that some clients may display the messages later than expected, not at all, or immediately overwrite it with something else. While we can't do much about the clients themselves in this project, we'd nonetheless like to hear about your experience, preferably with as many clients as possible!

**Comment by LDVG** [comment]
- After compiling, have you pointed the service configuration to your build of `pam_u2f.so`?
- What client are you attempting to authenticate with?

**Comment by LecrisUT** [comment]
I have copied it in place from `build/.lib/pam_u2f.so` to `/usr/lib64/security/pam_u2f.so`.

I have tried plain linux authenthication: `ctrl+alt+F4` and login after changing `authselect`

**Comment by LDVG** [comment]
For sanity checking: Was the build out of the `cue` branch? Is the `cue` flag present in the service configuration? What happens if you test through e.g. `sudo`?

**Comment by LDVG** [comment]
OK. Your modification will only print out an error if an authenticator _is_ found, but an error occurs when trying to authenticate using it (e.g. user presence is not collected, PIN does not verify, etc.). To also print out an error message when _no_ authenticators are found, you need additional changes.

**Comment by LecrisUT** [comment]
Ok, with the `cue` branch. It does print out suitable error messages. Can mark that PR to close this issue
