### ISSUE TITLE
pam-u2f saying that my token doesn't have a pin even so a pin is set.

### ISSUE THREAD

**Issue by Janik-Haag** [Yubico/pam-u2f#297]
### What version of pam-u2f are you using?
pamu2fcfg 1.3.0
Installed the [nix-package](https://search.nixos.org/packages?channel=unstable&show=pam_u2f&from=0&size=50&sort=relevance&type=packages&query=pam-u2f)
### What operating system are you using?
Linux - NixOS

libfido2 version: 1.13.0

### What authenticator are you using?

```
fido2-token -L
/dev/hidraw1: vendor=0x1050, product=0x0407 (Yubico YubiKey OTP+FIDO+CCID)
```
```
fido2-token -I /dev/hidraw1   
proto: 0x02
major: 0x05
minor: 0x04
build: 0x03
caps: 0x05 (wink, cbor, msg)
version strings: U2F_V2, FIDO_2_0, FIDO_2_1_PRE
extension strings: credProtect, hmac-secret
transport strings: nfc, usb
algorithms: es256 (public-key), eddsa (public-key)
aaguid: 2fc0579f811347eab116bb5a8db9202a
options: rk, up, noplat, noclientPin, credentialMgmtPreview
fwversion: 0x50403
maxmsgsiz: 1200
maxcredcntlst: 8
maxcredlen: 128
maxlargeblob: 0
minpinlen: 4
pin protocols: 2, 1
pin retries: undefined
pin change required: false
uv retries: undefined
```

### Problem description
I'm trying to setup my `~/.config/Yubico/u2f_keys` with one of my yubikeys. Just doing `pamu2fcfg > ~/.config/Yubico/u2f_keys` works fine but I would like pin verfication, so I'm doing `pamu2fcfg -N > ~/.config/Yubico/u2f_keys` which dosn't work and throws this error: `pamu2fcfg: device has no PIN`. Even tho I used `ykman piv access change-pin` wich outputs this:
```
ykman piv access change-pin             
Enter the current PIN: 
Enter the new PIN: 
Repeat for confirmation: 
New PIN set.
```
So the yubikey has a pin set but pam-u2f does says that it doesn't have a pin.

**Comment by LDVG** [comment]
Hi,

Each application on the YubiKey has separate PIN:s. If you would like to set a PIN for the FIDO applet (which this project uses for authentication), please use use the `ykman fido access change-pin` command (note `fido` vs `piv`). For more information on YubiKey PIN:s, please see https://support.yubico.com/hc/en-us/articles/4402836718866-Understanding-YubiKey-PINs

Hope this helps.

**Comment by Janik-Haag** [comment]
Sorry for the in convince, this was clearly user error :see_no_evil:
