### ISSUE TITLE
./configure fails

### ISSUE THREAD

**Issue by afontaine** [Yubico/pam-u2f#30]
Trying to build from the git release tarball, and the configure script fails with the following:

```sh
...
checking for security/pam_modules.h... yes
checking for security/_pam_macros.h... yes
checking for security/pam_modutil.h... yes
checking for pam_start in -lpam... yes
./configure: line 12047: syntax error near unexpected token `LIBU2FHOST,'
./configure: line 12047: `PKG_CHECK_MODULES(LIBU2FHOST, u2f-host, , )'
```

Not sure if I'm missing a library or not.

EDIT: I'm on Debian Jessie, 64-bit.

**Comment by gktrk** [comment]
I believe you don't have pkg-config installed on your system and the PKG_CHECK_MODULES macro isn't properly expanding. Can you double check?

**Comment by afontaine** [comment]
Yeah that's exactly what it was. Thanks! I guess `pkg-config` should be added to the README?
