### ISSUE TITLE
Multiple U2F keys

### ISSUE THREAD

**Issue by pavelkogan** [Yubico/pam-u2f#31]
I'm only able to register one key.

When I specify two keys in `u2f_keys` as so:

    <username1>:<KeyHandle1>,<UserKey1>:<KeyHandle2>,<UserKey2>

Only one of the keys works. If I switch the order of the keys in the file, then the other key works, but the first stops working.

I'm using the version from the PPA on Ubuntu 15.10.

**Comment by a-dma** [comment]
We found a problem in libu2f-host causing this. Commit Yubico/libu2f-host@82d7b52d10fc8085bc5e838f3de1cedf3e41ebbf fixes the problem. If you're build your version off of HEAD it is fixed there. However, at this stage, we haven't released yet as we are still looking into another minor issue.

**Comment by pavelkogan** [comment]
OK, good to know, thanks.
