### ISSUE TITLE
appid to default to origin?

### ISSUE THREAD

**Issue by candlerb** [Yubico/pam-u2f#34]
This one confused me a lot.

* Using `pamu2fcfg -o https://example.com -u brian >kkk`, things didn't work
* Using `pamu2fcfg -o https://example.com -i https://example.com -u brian >kkk` then everything worked

I think what's happening is the `-i` (appid) flag is still defaulting to `pam://<hostname>` even if you specify a different origin.

This is inconsistent with the behaviour of the pam-u2f module itself, where if you specify only the origin, the appid defaults to the origin.

So I think it would be better if pamu2fcfg worked the same way: specifying `-o` without `-i` should set both origin and appid to the given value.

**Comment by a-dma** [comment]
Makes sense. Thanks.
