### ISSUE TITLE
u2f with SSH

### ISSUE THREAD

**Issue by Padnezz** [Yubico/pam-u2f#35]
I'm trying to work out how to use U2F Authentication with SSH, the only thing I am able to find is an old issue that uses an old OpenSSH version. 

Does anyone know if there is a way to implement U2F Authentication with the current version of OpenSSH?

**Comment by nbraud** [comment]
No: `pam-u2f` let's you authenticate using a local U2F token.
In your usecase, the token is on the remote client (from the server's perspective).

See #12

**Comment by nbraud** [comment]
PS: In principle, you can use it remotely with the `manual` options, but the UX is very poor.

**Comment by Padnezz** [comment]
Ah, okay
