### ISSUE TITLE
PAM config profile

### ISSUE THREAD

**Issue by mhalano** [Yubico/pam-u2f#36]
The pam-u2f should have a file inside /usr/share/pam-configs/ so it will be possible use the command "sudo pam-auth-update". Most of PAM modules have a file there.

**Comment by gdamjan** [comment]
On what distro?

**Comment by mhalano** [comment]
@gdamjan I checked again and the file was generated. Sorry for this silly issue. :)

**Comment by chiraag-nataraj** [comment]
Hmmm, on Debian, there is no file in `/usr/share/pam-configs`, so it's not possible to manage this module using `pam-auth-update`. Is this an issue with the packaging for Debian or is this file no longer included upstream?

**Comment by LDVG** [comment]
@chiraag-nataraj: Yubico has, to my knowledge, never distributed such a file for `pam-u2f`. I do not know if Debian's packaging of 
`pam-u2f` has included such a file at some point.

**Comment by chiraag-nataraj** [comment]
Would it be possible to reopen this issue then? I think including such a file would be great for proper integration with the rest of PAM.

**Comment by LDVG** [comment]
We have an open issue for this over at Yubico/pam-u2f-dpkg#4. :slightly_smiling_face:
