### ISSUE TITLE
Unable to discover device under Mac OS El Capitan

### ISSUE THREAD

**Issue by zero-one-devteam** [Yubico/pam-u2f#39]
On Mac OS El Capitan (10.11.6), we'll get the following debug message:

debug: pam-u2f.c:209 (pam_sm_authenticate): Using default authentication file /Users/john/.config/Yubico/u2f_keys
debug: util.c:107 (get_devices_from_authfile): Authorization line: john:<long code>
debug: util.c:112 (get_devices_from_authfile): Matched user: john
debug: util.c:130 (get_devices_from_authfile): KeyHandle for device number 1: <long code>
debug: util.c:157 (get_devices_from_authfile): publicKey for device number 1: <long code>
debug: util.c:172 (get_devices_from_authfile): Length of key number 1 is 65
debug: util.c:200 (get_devices_from_authfile): Found 1 device(s) for user john
debug: util.c:252 (do_authentication): Unable to discover device(s), cannot find U2F device
debug: pam-u2f.c:256 (pam_sm_authenticate): do_authentication returned -2

Obviously, the user was found, but after that the device could not be found. Moving the authfile to /etc did not solve the problem. 

The /etc/pam.d/su:

auth       required       /usr/local/Cellar/pam-u2f/1.0.4/lib/pam/pam_u2f.so debug
auth       sufficient     pam_rootok.so
auth       required       pam_opendirectory.so
account    required       pam_group.so no_warn group=admin,wheel ruser root_only fail_safe
account    required       pam_opendirectory.so no_check_shell
password   required       pam_opendirectory.so
session    required       pam_launchd.so

When using pam-u2f in /etc/pam.d/screensaver we also often see the problem that we have to authenticate several times before it works and after that the system seems to be in a state like after a reboot (all previous opened programms restart)

**Comment by a-dma** [comment]
Looks like your device is not recognized at all.

Can you get U2F to work elsewhere? Say with https://demo.yubico.com/u2f ?

**Comment by zero-one-devteam** [comment]
Yes we got it working with openvpn, Dropbox and with your test link without problems. After several authentication tries it works wit pam as well, but not at the first try. We tested on a MacBook Pro late 2015 and MacBook 2016.

**Comment by zero-one-devteam** [comment]
For U2F it does not matter how the Yubikey is configured, right? Means, we have a static password on slot 1 and OTP on slot 2. That should not cause any problems I guess ...

**Comment by a-dma** [comment]
> For U2F it does not matter how the Yubikey is configured, right? Means, we have a static password on slot 1 and OTP on slot 2. That should not cause any problems I guess ...

Correct, that doesn't make any difference as long as the U2F mode is enabled.

It looks like `libu2f_host` can't find your device. Try enabling debug on that.

Unfortunately `pam_u2f` itself doesn't allow you to turn on debug for `libu2f_host`, but `pamu2fcfg` does. The purpose of the tool is to do registration, but the `init` call is the same. Run it with `pamu2fcfg -d` and see if you can replicate the issue.

**Comment by zero-one-devteam** [comment]
I will shorten the output of pamu2fcfg -d:

...
Device found!
...
USB send: 000100d56c8300470001030000004062f458c5e277bf248feeca30a44b917580cceff9b63d2af25e5bb200b0bb38851da7dd24194a5469f9e2c29f8e59dc7170
USB write returned 65
USB send: 000100d56c00411eef01e6bf8c5df1bfb95500180000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
USB write returned 65
now trying with timeout 2
now trying with timeout 4
now trying with timeout 8
USB read rc read 64
USB recv: 0100d56c830002698500000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
USB data (len 2): 6985
USB send: 000100d56c8300470001030000004062f458c5e277bf248feeca30a44b917580cceff9b63d2af25e5bb200b0bb38851da7dd24194a5469f9e2c29f8e59dc7170
USB write returned 65
USB send: 000100d56c00411eef01e6bf8c5df1bfb95500180000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
USB write returned 65
now trying with timeout 2
now trying with timeout 4
now trying with timeout 8
...
Unable to generate registration challenge, timeout error (-7)

Hmmm, what does that mean?

**Comment by a-dma** [comment]
That looks like good output to me.
The timeout is because you haven't touched the YubiKey, but the device was found.

**Comment by zero-one-devteam** [comment]
Yes, you're right, of course. What I found out: sometimes the device is not found and after several failed logins (the device does not blink after entering username and password) my user will be logged out by the system. So I wonder, why the device is not found. First, I guessed there are some issues with filevault2 which I have enabled. But the problem also occurs while logged in and using su (I have configured /etc/pam.d/su to test). What's weird is that it sometimes works and sometimes does not. Makes it very difficult to debug.

**Comment by a-dma** [comment]
Can you get the same behavior (device not found) with `pamu2fcfg -d` ? In that case the debug info might help.

Also, have you noticed any correlation between when the issue arises and whether or not the device was already plugged in vs just plugged in?

**Comment by zero-one-devteam** [comment]
Tried pamu2fcfg -d several times without any problems. Problem with pam occurred when the device was already plugged in. It did not start blinking after entering username and password after leaving the screensaver or standby. Could not reproduce it with plugging it in on demand, but I guess that's only a matter of how often I will try.

Is it possible to write the debug to a log file as well? When using it with /etc/pam.d/screensaver I won't get debug information otherwise.

**Comment by a-dma** [comment]
Currently is only possible to dump debug info to stderr. Maybe I should add a logfile option.

So, there is a problem with libhidapi on Mac where if you have a composite HID device, sometimes the path generated is wrong and you end up opening the wrong device. Would you mind turning off the OTP module in your NEO and see if that solves the problem?

**Comment by zero-one-devteam** [comment]
How can I disable OTP? I think I have to configure the slot (in my case it's slot 2) with a static password or can I completely disable it?

**Comment by a-dma** [comment]
You can disable it with either yubikey-neo-manager (GUI) or ykneomgr (CLI).

We have Mac releases for them. Check developers.yubico.com

**Comment by zero-one-devteam** [comment]
I've disabled OTP, but it does not make any difference. Sometimes, Yubikey will be detected as u2f device, other times it won't, than the debug shows:

debug: util.c:200 (get_devices_from_authfile): Found 1 device(s) for user andreas
debug: util.c:252 (do_authentication): Unable to discover device(s), cannot find U2F device

With pamu2fcfg -d it will always be detected, sometimes after 3-6 seconds ... Maybe the pam module times out too early?

**Comment by zero-one-devteam** [comment]
I could change to challenge-response mode as decribed here: https://developers.yubico.com/yubico-pam/MacOS_X_Challenge-Response.html

But in fact thats not what would help me, because I need both, OTP (for OpenVPN) and staticPassword and the Yubikey only provides 2 slots ...

**Comment by zero-one-devteam** [comment]
Hmmm, when OTP is disabled, u2f works fine (I had to delete my former posting). As soon as OTP is re-activated, u2f shows the behaviour as before, means sometimes working, other times not.

Problem: I need OTP as well (for openvpn, as there are no reliable u2f implementations yet) and I don't line to use a second Yubikey ...

**Comment by a-dma** [comment]
Yes, this sounds like the issue I described before with `libhidapi` (which `pam-u2f` uses).
Not much we can do at this point, besides rewriting `libu2f-host` to use a native implementation rather than a library, but that would be a major undertaking at this stage.

**Comment by zero-one-devteam** [comment]
Ok, thanks for supporting me. So, I will switch to challenge response mode as described here:

https://www.yubico.com/wp-content/uploads/2016/02/Yubico_YubiKeyMacOSXLogin_en.pdf

This seems to be very reliable and offers similar security.

**Comment by blahgeek** [comment]
@a-dma Is it possible to call `ykpersonalize -m 3` (set device to u2f only) when pam_u2f.so init, and call `ykpersonalize -m 6` when it's complete?

**Comment by blahgeek** [comment]
@zero-one-devteam @a-dma It seems that current master version of hidapi resolved this issue (https://github.com/signal11/hidapi/pull/40)

**Comment by zero-one-devteam** [comment]
Thanks for getting back to me. I installed the new hidapi as described there but the problem is still present. Maybe I've missed something. libhidapi can be found in /usr/local/lib. Is that the place where pam-u2f is looking for?

**Comment by a-dma** [comment]
It depends if you have multiple install of the library and how your system is setup. You can find out by calling `ldd` on `pam-u2f.so`

**Comment by zero-one-devteam** [comment]
That's what confuses me. I am on Mac OS X, so I have to use otool -L which shows me:
/usr/local/opt/libu2f-host/lib/libu2f-host.0.dylib (compatibility version 1.0.0, current version 1.5.0)
	/usr/local/opt/libu2f-server/lib/libu2f-server.0.dylib (compatibility version 1.0.0, current version 1.3.0)
	/usr/lib/libpam.2.dylib (compatibility version 3.0.0, current version 3.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1226.10.1)

No libhidapi ...

**Comment by blahgeek** [comment]
I'm using homebrew, `brew install --HEAD hidapi` and `brew install pam-u2f` works for me.

**Comment by zero-one-devteam** [comment]
Interesting. Did not work for me. I had to compile hidapi manually and replace the libs that have been installed by brew before.
