### ISSUE TITLE
A plea-

### ISSUE THREAD

**Issue by seajayproton** [Yubico/pam-u2f#47]
Not so much an "issue" but a plea from those of us who are NOT gifted systems engineers but have a NEED for a tool such as this. 

Could some gifted person not knock up an executable or even a basic GUI interface. Or even a "Step 1 - step-2" instruction for dummies note. I appreciate you value your free time - so do I suspect use would be more extended if it were easier to use.

I would LOVE to implement pam-u2f to use the yubikeys I have to block access to linux PC's. I'm new to Linux and whilst I have some fairly good IT skills they are MAINFRAME skills. 

I am going to write to the MINT admin guys to see if they can somehow assist too.

My thanks for your attention. Chris

**Comment by a-dma** [comment]
The examples ins the README file, are they not helpful enough? A GUI for PAM is a tricky concept since all you have to do is edit configuration files.

**Comment by AdrianKoshka** [comment]
I've written a short guide for using pam-u2f as 2FA for logging into *nix boxes. https://github.com/nixheads/trivial_docs/blob/master/docs/security/2fa/fido-u2f-pam.md
