### ISSUE TITLE
Ubuntu PPA broken (missing .so file)

### ISSUE THREAD

**Issue by catskul** [Yubico/pam-u2f#6]
https://launchpad.net/~yubico/+archive/ubuntu/stable/+packages
https://launchpad.net/~yubico/+archive/ubuntu/stable/+build/6688622

Does not contain `pam_u2f.so`

Examining the build log provides the following hint which may be related:

    libtool: install: warning: remember to run `libtool --finish /lib/x86_64-linux-gnu/security'

**Comment by a-dma** [comment]
New version on PPA

**Comment by catskul** [comment]
Awesome! I'll try it out tonight.
