### ISSUE TITLE
Cue appearing in lightdm with unity greeter after touching key

### ISSUE THREAD

**Issue by travelerjjm** [Yubico/pam-u2f#66]
I am using a generic Ubuntu 16.04 VM under VirtualBox. I installed pamu2fcfg and use m Yubico key to successfully authenticate using su and to lightdm with the Unity greeter. But When I login with the greeter, the cue shows up properly only *after* I touch the device, not after entering the password as I would expect. This occurs regardless of where I place the 
auth sufficient pam_u2f.so cue
line in /etc/pam.d/lightdm. Am I doing something wrong or is pam_u2f.so not interacting with unity correctly? (Or is unity/lightdm misbehaving?)
Thanks.

**Comment by KazWolfe** [comment]
Confirmed on lightdm 1.18.3.

After entering my password, LightDM drops down into a blank prompt and my key blinks. I touch the key, and the system will jump to saying "Please touch the device" with the Log In button. Pressing Log In works as expected.

This would seem more like a Unity bug to me, but there might be something `pam-u2f` can do to circumvent that.

**Comment by a-dma** [comment]
Hi,

this project is being rewritten and will only receive security updates.
