### ISSUE TITLE
MacOS: attempting to login when u2f is required w/o key inserted causes logout

### ISSUE THREAD

**Issue by kristovatlas** [Yubico/pam-u2f#71]
I'm testing pam-u2f (thanks!) installed via homebrew on MacOS.

I have /etc/pam.d/authorization and /etc/pam.d/screensaver configured to require pam-u2f:
`auth       required       /usr/local/Cellar/pam-u2f/1.0.4/lib/pam/pam_u2f.so authfile=/Users/username/.config/u2f/keys`

It generally works very well, but I've noticed that if I try to unlock the machine from the password-protected screensaver with my password only and no U2F key inserted, this happens next:
1. The login fails
2. If I insert the U2F key and re-try, the login momentarily appears to progress, but then I'm logged out and return to the screen that selects a user to login with.

Frustratingly and inexplicably, this always results in my Google Chrome preference file becoming corrupted, even if I don't have Google Chrome open.

The fact that the user is logged out if they forget to insert the key is a serious impediment to encouraging users under my purview to use pam-u2f.

Oddly, I never noticed this behavior with pam_yubico.so configured as required for both pam files in `mode=challenge-response`.

Machine: MBP
OS: 10.11.6 (El Capitan)
U2F device: Yubico FIDO U2F Security Key

**Comment by a-dma** [comment]
Hi,

I would have to assume that this behavior is dictated by how MacOS reacts to specific errors from the module. It would be interesting if you could grab a debug output of the whole process.

**Comment by kristovatlas** [comment]
Can you recommend a source of debug data?

**Comment by a-dma** [comment]
You can use the `debug` flag in the module itself. Keep in mind that this enables debugging to stderr, so using this for something like a login facility might be a bit tricky...

**Comment by kristovatlas** [comment]
@a-dma My expectation is that the stdout won't be captured in any log files. Any chance you can add an additional option to the module that permits logging to a file rather than to stdout? This seems like it would be generally useful for debugging given that stdout is often not accessible during an authentication process.

**Comment by a-dma** [comment]
Pushed some code to do that. Hopefully it helps.

**Comment by c00kiemon5ter** [comment]
I am running Sierra/10.12.6 and it seems to be working fine.
