### ISSUE TITLE
MacOS: cannot authenticate installers as admin user 

### ISSUE THREAD

**Issue by kristovatlas** [Yubico/pam-u2f#72]
I have a MacOS machine requiring pam-u2f for /etc/pam.d/authorization and /etc/pam.d/authorization.

I have two users on that system -- user1 and user2.

user1 is a local administrator account, while user2 is a local non-admin account.

I set up u2f using `pamu2fcfg` while logged into user2. The resulting authorization mapping file was stored in `/Users/user2/.config/u2f/keys`.

Later, I manually edited the `keys` file to duplicate the first line but add user1 as another authorized user of that key:
`keys`:
```
user2:<key handle>,<public key>
user1:<same key handle>,<same public key>
```

Now, if I run an installer application requiring admin privileges while logged into user2 in MacOS, here's the behavior I **expect**:
1. I enter my admin username (user1) and password, and hit OK.
2. The U2F key already inserted prompts me for proof-of-presence. Once pressed, the installer should be authorized with admin privs.

Instead, this happens:
1. I enter my admin username (user1)/password and hit OK.
2. I am immediately rejected with the MacOS shaking animation inside the authorization prompt. It doesn't appear that the u2f key is interacted with at all.
3. The following lines are appended to log files

`/var/log/system.log`: 
`Apr  3 16:23:38 computername authorizationhost[1858]: Failed to authenticate user <user1> (error: 12).` 

`/var/log/accountpolicy.log`: 
`Apr  3 16:23:38 (74.75.1) AuthenticationAllowed completed: record "user1", result: Success (0).`

I don't think it's a file permissions issue with the authorization mapping file; I gave user1 read and write access to `/Users/user2/`, `/Users/user2/.config/`, `/Users/user2/.config/u2f/`, and `/Users/user2/.config/u2f/keys`.

I haven't had this issue with pam_yubico.so configured as required for both pam files in `mode=challenge-response`.

**Comment by a-dma** [comment]
the README specifies that the file in .config should have only one entry. You can get more info by turning on debug info. I just pushed some code to allow debugging to a specific file rather than STDOUT.

**Comment by kristovatlas** [comment]
@a-dma doesn't the README specify that you can have a mapping for multiple users?

https://github.com/Yubico/pam-u2f#central-authorization-mapping

I'll check out the debug output when I get a chance, thank you.
