### ISSUE TITLE
No u2f-host found?!

### ISSUE THREAD

**Issue by solotim** [Yubico/pam-u2f#73]
Hi, 
I'm following this instruction to install pam-u2f:
https://developers.yubico.com/pam-u2f/

I also manually installed pkg-config, as mentioned in one of the closed issues.

u2f-host is also installed through apt-get, since I've added the ppa source.

But, the ./configure always complains "No package 'u2f-host' found". I'm sure it's installed well (/usr/bin/u2f-host) Could you please help? Thanks

**Comment by AdrianKoshka** [comment]
You probably need the appropriate developmental packages. Though a fair few Linux distros already package all the U2F packages needed (I have  the u2f-pam stuff installed on a personal machine). I know ubuntu and Debian stretch do.

**Comment by solotim** [comment]
Thanks. I'm using Lubuntu (LXDE Ubuntu). Could you point out which specific dev package I need to install?

**Comment by AdrianKoshka** [comment]
I happen to be on Lubuntu also :p 

`libu2f-host-dev` is probably what it's looking for.

Though if you just want to install the PAM stuff through your package manager there's: 
`libpam-u2f/zesty`

**Comment by solotim** [comment]
Thanks.
It's solved. Both libu2f-host-dev, libu2f-server-dev need to be installed upfront.

But, the "make" failed with:
_/bin/bash /home/feng/Downloads/pam-u2f/build-aux/missing a2x --format=manpage -L -a revdate="Version 1.0.5" man/pam_u2f.8.txt

a2x: ERROR: "xsltproc"  --stringparam callout.graphics 0 --stringparam navig.graphics 0 --stringparam admon.textlabel 1 --stringparam admon.graphics 0  "/etc/asciidoc/docbook-xsl/manpage.xsl" "/home/feng/Downloads/pam-u2f/man/pam_u2f.8.xml" returned non-zero exit status 5_

I couldn't find answer by google. But the corporation service I'm using works fine without installing pam-u2f at all. Anyway I'm happy my box is working now.
