### ISSUE TITLE
Don't require ENTER when using Interactive mode

### ISSUE THREAD

**Issue by KazWolfe** [Yubico/pam-u2f#74]
The `interactive` mode is very useful to prompt people to remember to insert their key. However, it also has the issue of requiring the ENTER button be pressed.

Would it be possible to have the authentication system poll for the insertion of a key if `interactive` is enabled instead of having the user take an action? Similarly, this could solve the problem of a user hitting enter "too early" (immediately after inserting their key, before initialization).

**Comment by a-dma** [comment]
Hi,

thanks for the idea. This project is being rewritten.
We'll try to incorporate that into the new version.
