### ISSUE TITLE
[Question] Detecting that Yubikey is waiting for a touch via an external script

### ISSUE THREAD

**Issue by maximbaz** [Yubico/pam-u2f#77]
I have YubiKey 4 Nano and the blinking light is not always visible, so I often find myself missing a time window to touch Yubikey when there is a prompt "Please touch the device". This happens for example when I begin some long-running task that will finish with a sudo command (e.g. build and install an app).

I'd like to write an external script that could somehow check every second if there is a pending sudo command that is waiting with "Please touch the device" message. Could you please give me any hints on how to achieve this? Maybe there is a temporary file created that I could watch, or maybe I could patch the `pam-u2f` somehow for this purpose?

I already managed to write such script that captures if YubiKey is waiting for a touch for a `gpg` command, now I only need to detect pending touch for a sudo command and that will make me completely happy 🙂

**Comment by maximbaz** [comment]
I have a partial success: because `pam-u2f` reads the `~/.config/Yubico/u2f_keys` every time before "Please touch the device" message appears, I can listen to when this file is being accessed using `inotify-watch` and show a visible indicator on the screen for the user to touch Yubikey. 

But I can't figure out how to detect when the user has actually fulfilled this request and touched the Yubikey, so that I can hide my indicator... 🤔

**Comment by a-dma** [comment]
Can't really think of an easy way of doing this.
Maybe using `pam_conv` to print messages and/or chain in some other module that can help you with producing observable side-effects?

**Comment by maximbaz** [comment]
If I understand this correctly, `pam_conv` can print messages, but it would require some extra magic to capture these messages from outside before I could produce some observable side-effects...

The easiest side-effect I can think of would be if the code could just immediately open and close a file when communication with the device is complete. Not to introduce any new files, the code could perhaps just open/close the same `u2f_keys`, the `inotifywatch` should be able to catch that. What do you think about this idea? 

If I were to place such code, where would it be? Is it correct to assume that the end of [util.c#do_authentication()](https://github.com/Yubico/pam-u2f/blob/d8959dd9692da0bc77a4594c50b2633a9f46e8c8/util.c#L232) is when the communication is complete? But that function doesn't know the path to `u2f_keys`... so maybe better place it when `do_authentication()` is being called from, after [this line](https://github.com/Yubico/pam-u2f/blob/d8959dd9692da0bc77a4594c50b2633a9f46e8c8/pam-u2f.c#L283)...

**Comment by a-dma** [comment]
I was mostly thinking about using an additional module to do that part. Have a look at something like http://www.linux-pam.org/Linux-PAM-html/sag-pam_exec.html.

Also, I don't mean to discourage you, but keep in mind that as stated in the README, this module it not being developed anymore and a rewrite is in process. That means that unless it's a security vulnerability, we won't be accepting any PR. Just so you know before you put time in this.
