### ISSUE TITLE
Compiling from source on Lubuntu 17.10

### ISSUE THREAD

**Issue by dlednik** [Yubico/pam-u2f#79]
I get this error when compiling from git source running `./configure` command

```
checking for security/pam_appl.h... yes
checking for security/pam_modules.h... yes
checking for security/_pam_macros.h... yes
checking for security/pam_modutil.h... yes
checking for pam_start in -lpam... yes
./configure: line 12696: syntax error near unexpected token `LIBU2FHOST,'
./configure: line 12696: `PKG_CHECK_MODULES(LIBU2FHOST, u2f-host, , )'
ledi@Ledi-EliteBook-2760p:~/GIT/pam-u2f$ 
```
p.s. `pkg-config` is installed on the system. That was suggested fix in older issue logged on debian.

**Comment by a-dma** [comment]
It works for me on Ubuntu 17.10,

what does `pkg-config --libs u2f-host` return?

**Comment by a-dma** [comment]
`u2f-host` is the command-line tool. To build you want `libu2f-host-dev` and `libu2f-server-dev` (which depend on `libu2f-host0` and `libu2f-server0`, like the tool).

**Comment by dlednik** [comment]
Installed `libu2f-host-dev` and `libu2f-server-dev`

```
ledi@Ledi-EliteBook-2760p:~/GIT/pam-u2f$ pkg-config --libs u2f-host
-lu2f-host
```

Configure still fails with same error

**Comment by a-dma** [comment]
Weird.

What version of `autoconf` are you running? I assume the same I have on my Ubuntu 17.10: 2.69-11.
Are you using any non-standard path? An different architecture?

Did you have `pkg-config` already installed when you started or did you add it later? Maybe try running `autoreconf -if` from within the project directory.

**Comment by dlednik** [comment]
```
ledi@Ledi-EliteBook-2760p:~/GIT/pam-u2f$ autoconf --version
autoconf (GNU Autoconf) 2.69
Copyright (C) 2012 Free Software Foundation, Inc.
License GPLv3+/Autoconf: GNU GPL version 3 or later
<http://gnu.org/licenses/gpl.html>, <http://gnu.org/licenses/exceptions.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by David J. MacKenzie and Akim Demaille.
```

No extra arch. no none standard paths (as far as I know).
It's a fresh ubuntu 17.10 install on old EliteBook 2760p.

Just followed instructions on the website, nothing else.

**Comment by dlednik** [comment]
```
ledi@Ledi-EliteBook-2760p:~/GIT/pam-u2f$ autoreconf -if
libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, 'build-aux'.
libtoolize: copying file 'build-aux/ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
libtoolize: copying file 'm4/libtool.m4'
libtoolize: copying file 'm4/ltoptions.m4'
libtoolize: copying file 'm4/ltsugar.m4'
libtoolize: copying file 'm4/ltversion.m4'
libtoolize: copying file 'm4/lt~obsolete.m4'
configure.ac:14: installing 'build-aux/compile'
configure.ac:10: installing 'build-aux/missing'
Makefile.am: installing 'build-aux/depcomp'
```

**Comment by a-dma** [comment]
;)

maybe you added `pkg-config` after running the first `autoreconf` and system didn't pick it up.

Glad it worked. Closing this. Feel free to reopen if needed.
