### ISSUE TITLE
PAM login fails after json-c updates to 0.13

### ISSUE THREAD

**Issue by nicholascw** [Yubico/pam-u2f#80]
Initially I discovered my well-configured PAM login GDM3 wasn't able to detect my yubikey 4, then I tried to walk through the configure documentation.
Then the following error reported:
```
pamu2fcfg: error while loading shared libraries: libjson-c.so.2: cannot open shared object file: No such file or director
```
Then I tried to have the new version "libjson-c.so.3.0.1" soft-linked to libjson-c.so.2, it reports segment fault.

System info:Linux 4.14.11-1-ARCH, Archlinux x86-64

**Comment by maximbaz** [comment]
Update `libu2f-server` to `1.1.0` 🙂

https://github.com/Yubico/libu2f-server/issues/32
