### ISSUE TITLE
Would like to see release 1.0.5

### ISSUE THREAD

**Issue by cjoster** [Yubico/pam-u2f#82]
I was recently debugging some pam u2f issues I've had for a while and learned that there are several new features (debug_file, fixes to nouserok to handle missing authfile) that (obviously) aren't in 1.0.4 on Fedora 27. I'd like to see a 1.0.5 including these new features and fixes.

**Comment by a-dma** [comment]
Agreed.

I'll try to make a release next week.

**Comment by a-dma** [comment]
1.0.5 is out.

**Comment by cjoster** [comment]
Cool. I have opened this[0] fedora bugzilla to bump the version.

[0] - https://bugzilla.redhat.com/show_bug.cgi?id=1568058
