### ISSUE TITLE
[RFE] Mechanism to store previous 2FA and permit relaxed authentication for a configurable duration

### ISSUE THREAD

**Issue by cjoster** [Yubico/pam-u2f#86]
The specific use case here is a workstation that auto-locks frequently.

2FA on every authentication can become cumbersome. Personally, I consider a cryptographic authentication as far better than a password authentication if either one were to be used alone. The problem is that the only ways to configure U2F is 2FA on every auth (cumbersome) or just permit the U2F token alone, simply because no finer-grained control is available.

Given the option of 2fa-every-auth, or one of either password OR u2f, it's too easy to configure U2F as `sufficient' and just use that to login, because no other option is available. And this begets the problem of a locked workstation and token being stolen.

What I'd like a mechanism to do is for a sysadmin to be able to say, "If you've 2FA's in the last X hours, and it's only for X services (unlock screensaver), and (optionally) present the same key, the token is sufficient. Consider the following pam configuration:

auth sufficient pam_u2f.so cue recent_check recent_file=/var/lib/u2f/u2f_history timeout=4h
auth requisite  pam_unix.so try_first_pass
auth sufficient pam_u2f.so cue nouserok recent_save recent_file=/var/lib/u2f_history

The idea is the first call to pam_u2f can fail quietly (PAM_IGNORE?) on the time boundary, and proceed with 2fa normally, but save the successful authentication into some file. You could also set the options in a way that you'd token-auth before password if that's what the sysadmin wanted.

I see two problems:

1) I don't know of a good way to guarantee that the 2fa actually occurred. My pam understanding might not be all that good. Although I suppose if built into this module, it would be no worse than configuring the u2f module to be the only mechanism.

2) I don't know how to be sure it's only used to unlock the workstation.

I tried to hack this together with pam_timestamp.so and was unsuccessful, plus it lacks capabilities even if I could get it to work.

**Comment by a-dma** [comment]
Honestly I would prefer to leverage PAM's composability for this and try to use another module to cache either the password itself, or the fact that a user successfully logged in within the last few hours.
This is mostly to avoid too much complexity in this module

Would something like https://github.com/google/libpam-policycache serve your purpose?

**Comment by cjoster** [comment]
I agree entirely that this would be considerable feature creep. I suppose caching the password is functionally equivalent to what I'm thinking, but only works if the key is configured to be checked after, rather than before the password--which isn't an issue, but it's contrary to most howto's on the web.

I think simply exporting some environment variables on a successful authentication (which device and or keyhandle was used successfully) would allow me to put together the functionality I'm looking for.  I'll keep investigating if this can be done in a sane way.
