### ISSUE TITLE
Feature request: signify when pam-u2f is waiting for a touch

### ISSUE THREAD

**Issue by maximbaz** [Yubico/pam-u2f#88]
I made a tool [yubikey-touch-detector](https://github.com/maximbaz/yubikey-touch-detector) that makes it possible to make a visible indication when a YubiKey is waiting for a user to touch the device to confirm an action.

In order to support pam-u2f, I need to have some clear indication, when pam-u2f starts waiting for a touch and when it stops waiting for a touch.

I prototyped a solution in https://github.com/Yubico/pam-u2f/pull/78, and while this approach has some shortcomings, it works well for me. However, I would like to see a better solution implemented so that people don't have to use my fork.

One better approach could be for example if pam-u2f would create `/var/run/user/$UID/pam-u2f-touch` to signify when it is waiting for a touch, and remove the file when the touch is no longer needed.

**Comment by a-dma** [comment]
Cool, for opening a separate issue.
Would you want to try making a PR? Otherwise I can look into it, but it'll probably be a while

**Comment by maximbaz** [comment]
I'll give it a try 😉
