### ISSUE TITLE
use $XDG_CONFIG_HOME rather than $HOME for storing data

### ISSUE THREAD

**Issue by bmillemathias** [Yubico/pam-u2f#9]
Hello,

that would be great if yubico could store data in the standard directory designed for storing config $XDG_CONFIG_HOME and if the variable doesn't exist used the default behavior.

reference documentation: http://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html

**Comment by a-dma** [comment]
Done! Check out 333166ebbd81c88b780354e18fade5ba87ac6415

Thanks for the pointer
