### ISSUE TITLE
Change cue message

### ISSUE THREAD

**Issue by SirWindfield** [Yubico/pam-u2f#90]
I would love to change the message that gets displayed when the `cue` parameter is passed to the module. Is there some way to do so?

**Comment by a-dma** [comment]
The current message is a static string that can't be changed. It would require a bit of work giving the user the possibility to customize that. Also I don't think it would add a lot.

Why are you trying to do this? Is it just cosmetic reasons or does it impair functionality?

**Comment by SirWindfield** [comment]
Purely cosmetic reasons.

**Comment by a-dma** [comment]
I don't think it would be a huge gain, but then again `prompt` already does something like that...

**Comment by SirWindfield** [comment]
I tried the prompt parameter out (`[prompt=New prompt]` but couldn't get pam to display it. How exactly does it work? :)

**Comment by a-dma** [comment]
That one is used for `interactive`, it then shows the same cue message regardless. Is that enough for you?

**Comment by SirWindfield** [comment]
I just tried it out. Sadly I want to change the cue text. To be exact I want to make it grey using ANSI. 
I wrote a custom patch for it yesterday, so this issue can be closed. I can try, however, to make a PR if that is ok, adding a new flag to specify the cue message.

**Comment by a-dma** [comment]
Scary place to add ANSI escape sequences if you ask me.
I'm not opposed to this in principle, I'm more afraid that we're approaching the "too many options" territory, but as long as we have sane enough defaults, it's probably OK.
