### ISSUE TITLE
pamu2fcfg fails with json_object_put: Assertion failed

### ISSUE THREAD

**Issue by helinko** [Yubico/pam-u2f#93]
The full error message with -d is: 
```
USB send: 00ffffffff8600080807060504030201000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
USB write returned 65
now trying with timeout 2
USB read rc read 64
USB recv: ffffffff86001108070605040302010800f900020101000100000000000000000000000000000000000000000000000000000000000000000000000000000000
device /dev/hidraw9 discovered as 'Yubikey NEO OTP+U2F+CCID'
  version (Interface, Major, Minor, Build): 2, 1, 1, 0  capFlags: 1
pamu2fcfg: json_object.c:189: json_object_put: Assertion `jso->_ref_count > 0' failed.
[1]    13940 abort      sudo pamu2fcfg -d
```
I run it as root as with normal user u2f devices are not found. Options do not seem to affect this. I'm running NixOS unstable so [this](https://github.com/NixOS/nixpkgs/blob/master/pkgs/os-specific/linux/pam_u2f/default.nix) should reflect the dependencies.

**Comment by a-dma** [comment]
I suspect this is the same as #80. I'm not familiar with NixOS, but from what I can tell it uses [this](https://github.com/NixOS/nixpkgs/blob/56904d7c423f2b13b37fbd29f39bbb4b52bc7824/pkgs/development/libraries/libu2f-server/default.nix) version of libu2f-server. Try using `1.1.0` instead.

**Comment by helinko** [comment]
Hmm yes, it seems to be using 1.0.1. I'll try updating it next week

**Comment by helinko** [comment]
Yup, works with the update. Thanks!
