### ISSUE TITLE
Feature Request: nullok option

### ISSUE THREAD

**Issue by NP-Hardass** [Yubico/pam-u2f#94]
Would be nice if pam-u2f checked if the user has a u2f_mapping and bypassed the module if there is no such mapping.  This would allow opt-in by users as opposed to forcing it globally.  For example, [yubico-pam](https://github.com/Yubico/yubico-pam) has added such an option  https://github.com/Yubico/yubico-pam/issues/97 which allows effectively makes the authentication with the yubikey dependent on whether the user has already configured one.

**Comment by a-dma** [comment]
Isn't the `nouserok` option enough to support this behavior?
You can also set per-user credentials and mark the module itself as optional in your policy if needed.

**Comment by NP-Hardass** [comment]
I read nouserok's description 

> Set to enable authentication attempts to succeed even if the user trying to authenticate is not found inside authfile or if authfile is missing/malformed.

to mean that all authentication succeeds, regardless of whether authfile works out.

If the intended meaning is supposed to be the same as my proposed nullok, whereby it succeeds A) successful u2f, B) no/malformed authfile, then I am a little confused as to why something is not working on my machine.

I have two users, foo and bar.  foo has a yubikey and authfile, bar does not.  There is no global authfile.

/etc/pam.d/system-auth
`
auth            requisite       pam_u2f.so      cue nouserok
auth            required        pam_unix.so
`

The intention would be that for foo, would be prompted for a yubikey, then would have to enter a unix password, and for bar, would just be prompted for a unix password (presumably nouserok should cause the pam_u2f module to succeed for this user)

 When I attempt that as foo, it works as intended.  When run as bar, I get

**Comment by NP-Hardass** [comment]
(Sorry about that, accidentally clicked "Close and comment")

**Comment by NP-Hardass** [comment]
OK, my apologies.  I just realized that 1.0.4 was stable in Gentoo, not the latest 1.0.6 >_<  1.0.6 works exactly as you described with nouserok as what I was requesting.

Sorry for the noise/mixup!

**Comment by a-dma** [comment]
No worries, glad it is fixed!
